// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: GetAvailableVisitingLogsOfStudentResponse.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAvailableVisitingLogsOfStudentResponse struct {
	state         protoimpl.MessageState                                 `protogen:"open.v1"`
	GroupData     []*GetAvailableVisitingLogsOfStudentResponse_GroupData `protobuf:"bytes,1,rep,name=groupData,proto3" json:"groupData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableVisitingLogsOfStudentResponse) Reset() {
	*x = GetAvailableVisitingLogsOfStudentResponse{}
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableVisitingLogsOfStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableVisitingLogsOfStudentResponse) ProtoMessage() {}

func (x *GetAvailableVisitingLogsOfStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableVisitingLogsOfStudentResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableVisitingLogsOfStudentResponse) Descriptor() ([]byte, []int) {
	return file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescGZIP(), []int{0}
}

func (x *GetAvailableVisitingLogsOfStudentResponse) GetGroupData() []*GetAvailableVisitingLogsOfStudentResponse_GroupData {
	if x != nil {
		return x.GroupData
	}
	return nil
}

type GetAvailableVisitingLogsOfStudentResponse_Group struct {
	state          protoimpl.MessageState                                          `protogen:"open.v1"`
	Uuid           string                                                          `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title          string                                                          `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Archived       int32                                                           `protobuf:"varint,3,opt,name=archived,proto3" json:"archived,omitempty"`
	Uuid_1         string                                                          `protobuf:"bytes,4,opt,name=uuid_1,json=uuid1,proto3" json:"uuid_1,omitempty"`
	Huinya         *GetAvailableVisitingLogsOfStudentResponse_Group_Huinya         `protobuf:"bytes,5,opt,name=huinya,proto3" json:"huinya,omitempty"`
	Semester       *GetAvailableVisitingLogsOfStudentResponse_Group_Semester       `protobuf:"bytes,6,opt,name=semester,proto3" json:"semester,omitempty"`
	Empty          string                                                          `protobuf:"bytes,8,opt,name=empty,proto3" json:"empty,omitempty"`
	UuidWithHuinya *GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya `protobuf:"bytes,9,opt,name=uuid_with_huinya,json=uuidWithHuinya,proto3" json:"uuid_with_huinya,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group) Reset() {
	*x = GetAvailableVisitingLogsOfStudentResponse_Group{}
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableVisitingLogsOfStudentResponse_Group) ProtoMessage() {}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableVisitingLogsOfStudentResponse_Group.ProtoReflect.Descriptor instead.
func (*GetAvailableVisitingLogsOfStudentResponse_Group) Descriptor() ([]byte, []int) {
	return file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group) GetArchived() int32 {
	if x != nil {
		return x.Archived
	}
	return 0
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group) GetUuid_1() string {
	if x != nil {
		return x.Uuid_1
	}
	return ""
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group) GetHuinya() *GetAvailableVisitingLogsOfStudentResponse_Group_Huinya {
	if x != nil {
		return x.Huinya
	}
	return nil
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group) GetSemester() *GetAvailableVisitingLogsOfStudentResponse_Group_Semester {
	if x != nil {
		return x.Semester
	}
	return nil
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group) GetEmpty() string {
	if x != nil {
		return x.Empty
	}
	return ""
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group) GetUuidWithHuinya() *GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya {
	if x != nil {
		return x.UuidWithHuinya
	}
	return nil
}

type GetAvailableVisitingLogsOfStudentResponse_GroupData struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	Group         *GetAvailableVisitingLogsOfStudentResponse_Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	A             int32                                            `protobuf:"varint,2,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                                            `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	Uuid          string                                           `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableVisitingLogsOfStudentResponse_GroupData) Reset() {
	*x = GetAvailableVisitingLogsOfStudentResponse_GroupData{}
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableVisitingLogsOfStudentResponse_GroupData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableVisitingLogsOfStudentResponse_GroupData) ProtoMessage() {}

func (x *GetAvailableVisitingLogsOfStudentResponse_GroupData) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableVisitingLogsOfStudentResponse_GroupData.ProtoReflect.Descriptor instead.
func (*GetAvailableVisitingLogsOfStudentResponse_GroupData) Descriptor() ([]byte, []int) {
	return file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetAvailableVisitingLogsOfStudentResponse_GroupData) GetGroup() *GetAvailableVisitingLogsOfStudentResponse_Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GetAvailableVisitingLogsOfStudentResponse_GroupData) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *GetAvailableVisitingLogsOfStudentResponse_GroupData) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *GetAvailableVisitingLogsOfStudentResponse_GroupData) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetAvailableVisitingLogsOfStudentResponse_Group_Huinya struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Huinya) Reset() {
	*x = GetAvailableVisitingLogsOfStudentResponse_Group_Huinya{}
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Huinya) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableVisitingLogsOfStudentResponse_Group_Huinya) ProtoMessage() {}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Huinya) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableVisitingLogsOfStudentResponse_Group_Huinya.ProtoReflect.Descriptor instead.
func (*GetAvailableVisitingLogsOfStudentResponse_Group_Huinya) Descriptor() ([]byte, []int) {
	return file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Huinya) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Huinya) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type GetAvailableVisitingLogsOfStudentResponse_Group_Semester struct {
	state         protoimpl.MessageState                                           `protogen:"open.v1"`
	Uuid          string                                                           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                                                           `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Huinya_1      *GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya `protobuf:"bytes,3,opt,name=huinya_1,json=huinya1,proto3" json:"huinya_1,omitempty"`
	Huinya_2      *GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya `protobuf:"bytes,4,opt,name=huinya_2,json=huinya2,proto3" json:"huinya_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Semester) Reset() {
	*x = GetAvailableVisitingLogsOfStudentResponse_Group_Semester{}
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Semester) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableVisitingLogsOfStudentResponse_Group_Semester) ProtoMessage() {}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Semester) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableVisitingLogsOfStudentResponse_Group_Semester.ProtoReflect.Descriptor instead.
func (*GetAvailableVisitingLogsOfStudentResponse_Group_Semester) Descriptor() ([]byte, []int) {
	return file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Semester) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Semester) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Semester) GetHuinya_1() *GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya {
	if x != nil {
		return x.Huinya_1
	}
	return nil
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Semester) GetHuinya_2() *GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya {
	if x != nil {
		return x.Huinya_2
	}
	return nil
}

type GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Variant       int32                  `protobuf:"varint,2,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya) Reset() {
	*x = GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya{}
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya) ProtoMessage() {}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya.ProtoReflect.Descriptor instead.
func (*GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya) Descriptor() ([]byte, []int) {
	return file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya) GetVariant() int32 {
	if x != nil {
		return x.Variant
	}
	return 0
}

type GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya) Reset() {
	*x = GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya{}
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya) ProtoMessage() {}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya.ProtoReflect.Descriptor instead.
func (*GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya) Descriptor() ([]byte, []int) {
	return file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescGZIP(), []int{0, 0, 1, 0}
}

func (x *GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_GetAvailableVisitingLogsOfStudentResponse_proto protoreflect.FileDescriptor

const file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDesc = "" +
	"\n" +
	"/GetAvailableVisitingLogsOfStudentResponse.proto\x12\amessage\"\xc4\b\n" +
	")GetAvailableVisitingLogsOfStudentResponse\x12Z\n" +
	"\tgroupData\x18\x01 \x03(\v2<.message.GetAvailableVisitingLogsOfStudentResponse.GroupDataR\tgroupData\x1a\xac\x06\n" +
	"\x05Group\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\barchived\x18\x03 \x01(\x05R\barchived\x12\x15\n" +
	"\x06uuid_1\x18\x04 \x01(\tR\x05uuid1\x12W\n" +
	"\x06huinya\x18\x05 \x01(\v2?.message.GetAvailableVisitingLogsOfStudentResponse.Group.HuinyaR\x06huinya\x12]\n" +
	"\bsemester\x18\x06 \x01(\v2A.message.GetAvailableVisitingLogsOfStudentResponse.Group.SemesterR\bsemester\x12\x14\n" +
	"\x05empty\x18\b \x01(\tR\x05empty\x12q\n" +
	"\x10uuid_with_huinya\x18\t \x01(\v2G.message.GetAvailableVisitingLogsOfStudentResponse.Group.UuidWithHuinyaR\x0euuidWithHuinya\x1a$\n" +
	"\x06Huinya\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\x1a\x9e\x02\n" +
	"\bSemester\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12c\n" +
	"\bhuinya_1\x18\x03 \x01(\v2H.message.GetAvailableVisitingLogsOfStudentResponse.Group.Semester.HuinyaR\ahuinya1\x12c\n" +
	"\bhuinya_2\x18\x04 \x01(\v2H.message.GetAvailableVisitingLogsOfStudentResponse.Group.Semester.HuinyaR\ahuinya2\x1a\x1e\n" +
	"\x06Huinya\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x1a>\n" +
	"\x0eUuidWithHuinya\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\avariant\x18\x02 \x01(\x05R\avariant\x1a\x8b\x01\n" +
	"\tGroupData\x12N\n" +
	"\x05group\x18\x01 \x01(\v28.message.GetAvailableVisitingLogsOfStudentResponse.GroupR\x05group\x12\f\n" +
	"\x01a\x18\x02 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x03 \x01(\x05R\x01b\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuidB\x11Z\x0f./proto;messageb\x06proto3"

var (
	file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescOnce sync.Once
	file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescData []byte
)

func file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescGZIP() []byte {
	file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescOnce.Do(func() {
		file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDesc), len(file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDesc)))
	})
	return file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDescData
}

var file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_GetAvailableVisitingLogsOfStudentResponse_proto_goTypes = []any{
	(*GetAvailableVisitingLogsOfStudentResponse)(nil),                       // 0: message.GetAvailableVisitingLogsOfStudentResponse
	(*GetAvailableVisitingLogsOfStudentResponse_Group)(nil),                 // 1: message.GetAvailableVisitingLogsOfStudentResponse.Group
	(*GetAvailableVisitingLogsOfStudentResponse_GroupData)(nil),             // 2: message.GetAvailableVisitingLogsOfStudentResponse.GroupData
	(*GetAvailableVisitingLogsOfStudentResponse_Group_Huinya)(nil),          // 3: message.GetAvailableVisitingLogsOfStudentResponse.Group.Huinya
	(*GetAvailableVisitingLogsOfStudentResponse_Group_Semester)(nil),        // 4: message.GetAvailableVisitingLogsOfStudentResponse.Group.Semester
	(*GetAvailableVisitingLogsOfStudentResponse_Group_UuidWithHuinya)(nil),  // 5: message.GetAvailableVisitingLogsOfStudentResponse.Group.UuidWithHuinya
	(*GetAvailableVisitingLogsOfStudentResponse_Group_Semester_Huinya)(nil), // 6: message.GetAvailableVisitingLogsOfStudentResponse.Group.Semester.Huinya
}
var file_GetAvailableVisitingLogsOfStudentResponse_proto_depIdxs = []int32{
	2, // 0: message.GetAvailableVisitingLogsOfStudentResponse.groupData:type_name -> message.GetAvailableVisitingLogsOfStudentResponse.GroupData
	3, // 1: message.GetAvailableVisitingLogsOfStudentResponse.Group.huinya:type_name -> message.GetAvailableVisitingLogsOfStudentResponse.Group.Huinya
	4, // 2: message.GetAvailableVisitingLogsOfStudentResponse.Group.semester:type_name -> message.GetAvailableVisitingLogsOfStudentResponse.Group.Semester
	5, // 3: message.GetAvailableVisitingLogsOfStudentResponse.Group.uuid_with_huinya:type_name -> message.GetAvailableVisitingLogsOfStudentResponse.Group.UuidWithHuinya
	1, // 4: message.GetAvailableVisitingLogsOfStudentResponse.GroupData.group:type_name -> message.GetAvailableVisitingLogsOfStudentResponse.Group
	6, // 5: message.GetAvailableVisitingLogsOfStudentResponse.Group.Semester.huinya_1:type_name -> message.GetAvailableVisitingLogsOfStudentResponse.Group.Semester.Huinya
	6, // 6: message.GetAvailableVisitingLogsOfStudentResponse.Group.Semester.huinya_2:type_name -> message.GetAvailableVisitingLogsOfStudentResponse.Group.Semester.Huinya
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_GetAvailableVisitingLogsOfStudentResponse_proto_init() }
func file_GetAvailableVisitingLogsOfStudentResponse_proto_init() {
	if File_GetAvailableVisitingLogsOfStudentResponse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDesc), len(file_GetAvailableVisitingLogsOfStudentResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetAvailableVisitingLogsOfStudentResponse_proto_goTypes,
		DependencyIndexes: file_GetAvailableVisitingLogsOfStudentResponse_proto_depIdxs,
		MessageInfos:      file_GetAvailableVisitingLogsOfStudentResponse_proto_msgTypes,
	}.Build()
	File_GetAvailableVisitingLogsOfStudentResponse_proto = out.File
	file_GetAvailableVisitingLogsOfStudentResponse_proto_goTypes = nil
	file_GetAvailableVisitingLogsOfStudentResponse_proto_depIdxs = nil
}
