// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: GetAvailableLessonsOfVisitingLogsResponse.proto

package message

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAvailableLessonsOfVisitingLogsResponse struct {
	state         protoimpl.MessageState                              `protogen:"open.v1"`
	Lessons       []*GetAvailableLessonsOfVisitingLogsResponse_Lesson `protobuf:"bytes,2,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableLessonsOfVisitingLogsResponse) Reset() {
	*x = GetAvailableLessonsOfVisitingLogsResponse{}
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableLessonsOfVisitingLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableLessonsOfVisitingLogsResponse) ProtoMessage() {}

func (x *GetAvailableLessonsOfVisitingLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableLessonsOfVisitingLogsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableLessonsOfVisitingLogsResponse) Descriptor() ([]byte, []int) {
	return file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescGZIP(), []int{0}
}

func (x *GetAvailableLessonsOfVisitingLogsResponse) GetLessons() []*GetAvailableLessonsOfVisitingLogsResponse_Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type GetAvailableLessonsOfVisitingLogsResponse_Lesson struct {
	state         protoimpl.MessageState                                   `protogen:"open.v1"`
	Attended      int32                                                    `protobuf:"varint,2,opt,name=attended,proto3" json:"attended,omitempty"`
	Lesson        *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson `protobuf:"bytes,3,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson) Reset() {
	*x = GetAvailableLessonsOfVisitingLogsResponse_Lesson{}
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson) ProtoMessage() {}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableLessonsOfVisitingLogsResponse_Lesson.ProtoReflect.Descriptor instead.
func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson) Descriptor() ([]byte, []int) {
	return file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson) GetAttended() int32 {
	if x != nil {
		return x.Attended
	}
	return 0
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson) GetLesson() *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson struct {
	state         protoimpl.MessageState                                           `protogen:"open.v1"`
	Uuid          string                                                           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Start         *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time    `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time    `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Subject       *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text    `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Type          *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text    `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Room          *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room    `protobuf:"bytes,6,opt,name=room,proto3" json:"room,omitempty"`
	Teacher       *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher `protobuf:"bytes,7,opt,name=teacher,proto3" json:"teacher,omitempty"`
	Huinya        *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya  `protobuf:"bytes,8,opt,name=huinya,proto3" json:"huinya,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) Reset() {
	*x = GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson{}
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) ProtoMessage() {}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson.ProtoReflect.Descriptor instead.
func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) Descriptor() ([]byte, []int) {
	return file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) GetStart() *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) GetEnd() *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) GetSubject() *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) GetType() *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) GetRoom() *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) GetTeacher() *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher {
	if x != nil {
		return x.Teacher
	}
	return nil
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson) GetHuinya() *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya {
	if x != nil {
		return x.Huinya
	}
	return nil
}

type GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time) Reset() {
	*x = GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time{}
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time) ProtoMessage() {}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time.ProtoReflect.Descriptor instead.
func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time) Descriptor() ([]byte, []int) {
	return file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text) Reset() {
	*x = GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text{}
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text) ProtoMessage() {}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text.ProtoReflect.Descriptor instead.
func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text) Descriptor() ([]byte, []int) {
	return file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Campus        string                 `protobuf:"bytes,3,opt,name=campus,proto3" json:"campus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room) Reset() {
	*x = GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room{}
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room) ProtoMessage() {}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room.ProtoReflect.Descriptor instead.
func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room) Descriptor() ([]byte, []int) {
	return file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescGZIP(), []int{0, 0, 0, 2}
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room) GetCampus() string {
	if x != nil {
		return x.Campus
	}
	return ""
}

type GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher struct {
	state         protoimpl.MessageState                                                      `protogen:"open.v1"`
	Uuid          string                                                                      `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                                                                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FamilyName    string                                                                      `protobuf:"bytes,3,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	MiddleName    *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher_MiddleName `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher) Reset() {
	*x = GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher{}
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher) ProtoMessage() {}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher.ProtoReflect.Descriptor instead.
func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher) Descriptor() ([]byte, []int) {
	return file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescGZIP(), []int{0, 0, 0, 3}
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher) GetMiddleName() *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher_MiddleName {
	if x != nil {
		return x.MiddleName
	}
	return nil
}

type GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya) Reset() {
	*x = GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya{}
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya) ProtoMessage() {}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya.ProtoReflect.Descriptor instead.
func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya) Descriptor() ([]byte, []int) {
	return file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescGZIP(), []int{0, 0, 0, 4}
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher_MiddleName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher_MiddleName) Reset() {
	*x = GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher_MiddleName{}
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher_MiddleName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher_MiddleName) ProtoMessage() {}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher_MiddleName) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher_MiddleName.ProtoReflect.Descriptor instead.
func (*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher_MiddleName) Descriptor() ([]byte, []int) {
	return file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescGZIP(), []int{0, 0, 0, 3, 0}
}

func (x *GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher_MiddleName) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_GetAvailableLessonsOfVisitingLogsResponse_proto protoreflect.FileDescriptor

const file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDesc = "" +
	"\n" +
	"/GetAvailableLessonsOfVisitingLogsResponse.proto\x12\amessage\"\xe3\n" +
	"\n" +
	")GetAvailableLessonsOfVisitingLogsResponse\x12S\n" +
	"\alessons\x18\x02 \x03(\v29.message.GetAvailableLessonsOfVisitingLogsResponse.LessonR\alessons\x1a\xe0\t\n" +
	"\x06Lesson\x12\x1a\n" +
	"\battended\x18\x02 \x01(\x05R\battended\x12X\n" +
	"\x06lesson\x18\x03 \x01(\v2@.message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.LessonR\x06lesson\x1a\xdf\b\n" +
	"\x06Lesson\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12[\n" +
	"\x05start\x18\x02 \x01(\v2E.message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.TimeR\x05start\x12W\n" +
	"\x03end\x18\x03 \x01(\v2E.message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.TimeR\x03end\x12_\n" +
	"\asubject\x18\x04 \x01(\v2E.message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.TextR\asubject\x12Y\n" +
	"\x04type\x18\x05 \x01(\v2E.message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.TextR\x04type\x12Y\n" +
	"\x04room\x18\x06 \x01(\v2E.message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.RoomR\x04room\x12b\n" +
	"\ateacher\x18\a \x01(\v2H.message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.TeacherR\ateacher\x12_\n" +
	"\x06huinya\x18\b \x01(\v2G.message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.HuinyaR\x06huinya\x1a\x1c\n" +
	"\x04Time\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x1a0\n" +
	"\x04Text\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x1aJ\n" +
	"\x04Room\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x16\n" +
	"\x06campus\x18\x03 \x01(\tR\x06campus\x1a\xec\x01\n" +
	"\aTeacher\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vfamily_name\x18\x03 \x01(\tR\n" +
	"familyName\x12t\n" +
	"\vmiddle_name\x18\x04 \x01(\v2S.message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Teacher.MiddleNameR\n" +
	"middleName\x1a\"\n" +
	"\n" +
	"MiddleName\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x1a$\n" +
	"\x06Huinya\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01bB\x11Z\x0f./proto;messageb\x06proto3"

var (
	file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescOnce sync.Once
	file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescData []byte
)

func file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescGZIP() []byte {
	file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescOnce.Do(func() {
		file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDesc), len(file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDesc)))
	})
	return file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDescData
}

var file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_GetAvailableLessonsOfVisitingLogsResponse_proto_goTypes = []any{
	(*GetAvailableLessonsOfVisitingLogsResponse)(nil),                                  // 0: message.GetAvailableLessonsOfVisitingLogsResponse
	(*GetAvailableLessonsOfVisitingLogsResponse_Lesson)(nil),                           // 1: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson
	(*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson)(nil),                    // 2: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson
	(*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Time)(nil),               // 3: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Time
	(*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Text)(nil),               // 4: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Text
	(*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Room)(nil),               // 5: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Room
	(*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher)(nil),            // 6: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Teacher
	(*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Huinya)(nil),             // 7: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Huinya
	(*GetAvailableLessonsOfVisitingLogsResponse_Lesson_Lesson_Teacher_MiddleName)(nil), // 8: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Teacher.MiddleName
}
var file_GetAvailableLessonsOfVisitingLogsResponse_proto_depIdxs = []int32{
	1,  // 0: message.GetAvailableLessonsOfVisitingLogsResponse.lessons:type_name -> message.GetAvailableLessonsOfVisitingLogsResponse.Lesson
	2,  // 1: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.lesson:type_name -> message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson
	3,  // 2: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.start:type_name -> message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Time
	3,  // 3: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.end:type_name -> message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Time
	4,  // 4: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.subject:type_name -> message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Text
	4,  // 5: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.type:type_name -> message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Text
	5,  // 6: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.room:type_name -> message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Room
	6,  // 7: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.teacher:type_name -> message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Teacher
	7,  // 8: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.huinya:type_name -> message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Huinya
	8,  // 9: message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Teacher.middle_name:type_name -> message.GetAvailableLessonsOfVisitingLogsResponse.Lesson.Lesson.Teacher.MiddleName
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_GetAvailableLessonsOfVisitingLogsResponse_proto_init() }
func file_GetAvailableLessonsOfVisitingLogsResponse_proto_init() {
	if File_GetAvailableLessonsOfVisitingLogsResponse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDesc), len(file_GetAvailableLessonsOfVisitingLogsResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetAvailableLessonsOfVisitingLogsResponse_proto_goTypes,
		DependencyIndexes: file_GetAvailableLessonsOfVisitingLogsResponse_proto_depIdxs,
		MessageInfos:      file_GetAvailableLessonsOfVisitingLogsResponse_proto_msgTypes,
	}.Build()
	File_GetAvailableLessonsOfVisitingLogsResponse_proto = out.File
	file_GetAvailableLessonsOfVisitingLogsResponse_proto_goTypes = nil
	file_GetAvailableLessonsOfVisitingLogsResponse_proto_depIdxs = nil
}
