// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: GetAttendanceForLessonResponse.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAttendanceForLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*AttendanceStudent   `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttendanceForLessonResponse) Reset() {
	*x = GetAttendanceForLessonResponse{}
	mi := &file_GetAttendanceForLessonResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttendanceForLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendanceForLessonResponse) ProtoMessage() {}

func (x *GetAttendanceForLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GetAttendanceForLessonResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendanceForLessonResponse.ProtoReflect.Descriptor instead.
func (*GetAttendanceForLessonResponse) Descriptor() ([]byte, []int) {
	return file_GetAttendanceForLessonResponse_proto_rawDescGZIP(), []int{0}
}

func (x *GetAttendanceForLessonResponse) GetStudents() []*AttendanceStudent {
	if x != nil {
		return x.Students
	}
	return nil
}

type AttendanceStudent struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Id            string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                        `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                        `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Status        int32                         `protobuf:"zigzag32,4,opt,name=status,proto3" json:"status,omitempty"`
	MiddleName    *AttendanceStudent_MiddleName `protobuf:"bytes,6,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	Group         *AttendanceStudent_Group      `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	Uuid          string                        `protobuf:"bytes,9,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Huesos        int32                         `protobuf:"zigzag32,10,opt,name=huesos,proto3" json:"huesos,omitempty"`
	Card          string                        `protobuf:"bytes,11,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceStudent) Reset() {
	*x = AttendanceStudent{}
	mi := &file_GetAttendanceForLessonResponse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceStudent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceStudent) ProtoMessage() {}

func (x *AttendanceStudent) ProtoReflect() protoreflect.Message {
	mi := &file_GetAttendanceForLessonResponse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceStudent.ProtoReflect.Descriptor instead.
func (*AttendanceStudent) Descriptor() ([]byte, []int) {
	return file_GetAttendanceForLessonResponse_proto_rawDescGZIP(), []int{1}
}

func (x *AttendanceStudent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttendanceStudent) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AttendanceStudent) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AttendanceStudent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AttendanceStudent) GetMiddleName() *AttendanceStudent_MiddleName {
	if x != nil {
		return x.MiddleName
	}
	return nil
}

func (x *AttendanceStudent) GetGroup() *AttendanceStudent_Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *AttendanceStudent) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AttendanceStudent) GetHuesos() int32 {
	if x != nil {
		return x.Huesos
	}
	return 0
}

func (x *AttendanceStudent) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

type AttendanceStudent_MiddleName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceStudent_MiddleName) Reset() {
	*x = AttendanceStudent_MiddleName{}
	mi := &file_GetAttendanceForLessonResponse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceStudent_MiddleName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceStudent_MiddleName) ProtoMessage() {}

func (x *AttendanceStudent_MiddleName) ProtoReflect() protoreflect.Message {
	mi := &file_GetAttendanceForLessonResponse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceStudent_MiddleName.ProtoReflect.Descriptor instead.
func (*AttendanceStudent_MiddleName) Descriptor() ([]byte, []int) {
	return file_GetAttendanceForLessonResponse_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AttendanceStudent_MiddleName) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AttendanceStudent_Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Number        int32                  `protobuf:"zigzag32,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceStudent_Group) Reset() {
	*x = AttendanceStudent_Group{}
	mi := &file_GetAttendanceForLessonResponse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceStudent_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceStudent_Group) ProtoMessage() {}

func (x *AttendanceStudent_Group) ProtoReflect() protoreflect.Message {
	mi := &file_GetAttendanceForLessonResponse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceStudent_Group.ProtoReflect.Descriptor instead.
func (*AttendanceStudent_Group) Descriptor() ([]byte, []int) {
	return file_GetAttendanceForLessonResponse_proto_rawDescGZIP(), []int{1, 1}
}

func (x *AttendanceStudent_Group) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AttendanceStudent_Group) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_GetAttendanceForLessonResponse_proto protoreflect.FileDescriptor

const file_GetAttendanceForLessonResponse_proto_rawDesc = "" +
	"\n" +
	"$GetAttendanceForLessonResponse.proto\x12\amessage\"X\n" +
	"\x1eGetAttendanceForLessonResponse\x126\n" +
	"\bstudents\x18\x01 \x03(\v2\x1a.message.AttendanceStudentR\bstudents\"\x97\x03\n" +
	"\x11AttendanceStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x11R\x06status\x12F\n" +
	"\vmiddle_name\x18\x06 \x01(\v2%.message.AttendanceStudent.MiddleNameR\n" +
	"middleName\x126\n" +
	"\x05group\x18\a \x01(\v2 .message.AttendanceStudent.GroupR\x05group\x12\x12\n" +
	"\x04uuid\x18\t \x01(\tR\x04uuid\x12\x16\n" +
	"\x06huesos\x18\n" +
	" \x01(\x11R\x06huesos\x12\x12\n" +
	"\x04card\x18\v \x01(\tR\x04card\x1a\"\n" +
	"\n" +
	"MiddleName\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x1a:\n" +
	"\x05Group\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x11R\x06numberB\x11Z\x0f./proto;messageb\x06proto3"

var (
	file_GetAttendanceForLessonResponse_proto_rawDescOnce sync.Once
	file_GetAttendanceForLessonResponse_proto_rawDescData []byte
)

func file_GetAttendanceForLessonResponse_proto_rawDescGZIP() []byte {
	file_GetAttendanceForLessonResponse_proto_rawDescOnce.Do(func() {
		file_GetAttendanceForLessonResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetAttendanceForLessonResponse_proto_rawDesc), len(file_GetAttendanceForLessonResponse_proto_rawDesc)))
	})
	return file_GetAttendanceForLessonResponse_proto_rawDescData
}

var file_GetAttendanceForLessonResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_GetAttendanceForLessonResponse_proto_goTypes = []any{
	(*GetAttendanceForLessonResponse)(nil), // 0: message.GetAttendanceForLessonResponse
	(*AttendanceStudent)(nil),              // 1: message.AttendanceStudent
	(*AttendanceStudent_MiddleName)(nil),   // 2: message.AttendanceStudent.MiddleName
	(*AttendanceStudent_Group)(nil),        // 3: message.AttendanceStudent.Group
}
var file_GetAttendanceForLessonResponse_proto_depIdxs = []int32{
	1, // 0: message.GetAttendanceForLessonResponse.students:type_name -> message.AttendanceStudent
	2, // 1: message.AttendanceStudent.middle_name:type_name -> message.AttendanceStudent.MiddleName
	3, // 2: message.AttendanceStudent.group:type_name -> message.AttendanceStudent.Group
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_GetAttendanceForLessonResponse_proto_init() }
func file_GetAttendanceForLessonResponse_proto_init() {
	if File_GetAttendanceForLessonResponse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetAttendanceForLessonResponse_proto_rawDesc), len(file_GetAttendanceForLessonResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetAttendanceForLessonResponse_proto_goTypes,
		DependencyIndexes: file_GetAttendanceForLessonResponse_proto_depIdxs,
		MessageInfos:      file_GetAttendanceForLessonResponse_proto_msgTypes,
	}.Build()
	File_GetAttendanceForLessonResponse_proto = out.File
	file_GetAttendanceForLessonResponse_proto_goTypes = nil
	file_GetAttendanceForLessonResponse_proto_depIdxs = nil
}
