// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: GetAcademicGroupInfoResponse.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAcademicGroupInfoResponse struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Uuid          *GetAcademicGroupInfoResponse_UuidInfo   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Direction     *GetAcademicGroupInfoResponse_Direction  `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Deparment     *GetAcademicGroupInfoResponse_Department `protobuf:"bytes,6,opt,name=deparment,proto3" json:"deparment,omitempty"`
	Students      []*GetAcademicGroupInfoResponse_Student  `protobuf:"bytes,7,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAcademicGroupInfoResponse) Reset() {
	*x = GetAcademicGroupInfoResponse{}
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcademicGroupInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcademicGroupInfoResponse) ProtoMessage() {}

func (x *GetAcademicGroupInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcademicGroupInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAcademicGroupInfoResponse) Descriptor() ([]byte, []int) {
	return file_GetAcademicGroupInfoResponse_proto_rawDescGZIP(), []int{0}
}

func (x *GetAcademicGroupInfoResponse) GetUuid() *GetAcademicGroupInfoResponse_UuidInfo {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *GetAcademicGroupInfoResponse) GetDirection() *GetAcademicGroupInfoResponse_Direction {
	if x != nil {
		return x.Direction
	}
	return nil
}

func (x *GetAcademicGroupInfoResponse) GetDeparment() *GetAcademicGroupInfoResponse_Department {
	if x != nil {
		return x.Deparment
	}
	return nil
}

func (x *GetAcademicGroupInfoResponse) GetStudents() []*GetAcademicGroupInfoResponse_Student {
	if x != nil {
		return x.Students
	}
	return nil
}

type GetAcademicGroupInfoResponse_UuidInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Variant       int32                  `protobuf:"varint,2,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAcademicGroupInfoResponse_UuidInfo) Reset() {
	*x = GetAcademicGroupInfoResponse_UuidInfo{}
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcademicGroupInfoResponse_UuidInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcademicGroupInfoResponse_UuidInfo) ProtoMessage() {}

func (x *GetAcademicGroupInfoResponse_UuidInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcademicGroupInfoResponse_UuidInfo.ProtoReflect.Descriptor instead.
func (*GetAcademicGroupInfoResponse_UuidInfo) Descriptor() ([]byte, []int) {
	return file_GetAcademicGroupInfoResponse_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetAcademicGroupInfoResponse_UuidInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAcademicGroupInfoResponse_UuidInfo) GetVariant() int32 {
	if x != nil {
		return x.Variant
	}
	return 0
}

type GetAcademicGroupInfoResponse_Direction struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Uuid          string                                       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                                       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Code          *GetAcademicGroupInfoResponse_Direction_Code `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAcademicGroupInfoResponse_Direction) Reset() {
	*x = GetAcademicGroupInfoResponse_Direction{}
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcademicGroupInfoResponse_Direction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcademicGroupInfoResponse_Direction) ProtoMessage() {}

func (x *GetAcademicGroupInfoResponse_Direction) ProtoReflect() protoreflect.Message {
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcademicGroupInfoResponse_Direction.ProtoReflect.Descriptor instead.
func (*GetAcademicGroupInfoResponse_Direction) Descriptor() ([]byte, []int) {
	return file_GetAcademicGroupInfoResponse_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetAcademicGroupInfoResponse_Direction) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAcademicGroupInfoResponse_Direction) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetAcademicGroupInfoResponse_Direction) GetCode() *GetAcademicGroupInfoResponse_Direction_Code {
	if x != nil {
		return x.Code
	}
	return nil
}

type GetAcademicGroupInfoResponse_Department struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Department    string                 `protobuf:"bytes,2,opt,name=department,proto3" json:"department,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAcademicGroupInfoResponse_Department) Reset() {
	*x = GetAcademicGroupInfoResponse_Department{}
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcademicGroupInfoResponse_Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcademicGroupInfoResponse_Department) ProtoMessage() {}

func (x *GetAcademicGroupInfoResponse_Department) ProtoReflect() protoreflect.Message {
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcademicGroupInfoResponse_Department.ProtoReflect.Descriptor instead.
func (*GetAcademicGroupInfoResponse_Department) Descriptor() ([]byte, []int) {
	return file_GetAcademicGroupInfoResponse_proto_rawDescGZIP(), []int{0, 2}
}

func (x *GetAcademicGroupInfoResponse_Department) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAcademicGroupInfoResponse_Department) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *GetAcademicGroupInfoResponse_Department) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetAcademicGroupInfoResponse_Student struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Variant       int32                  `protobuf:"varint,3,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAcademicGroupInfoResponse_Student) Reset() {
	*x = GetAcademicGroupInfoResponse_Student{}
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcademicGroupInfoResponse_Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcademicGroupInfoResponse_Student) ProtoMessage() {}

func (x *GetAcademicGroupInfoResponse_Student) ProtoReflect() protoreflect.Message {
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcademicGroupInfoResponse_Student.ProtoReflect.Descriptor instead.
func (*GetAcademicGroupInfoResponse_Student) Descriptor() ([]byte, []int) {
	return file_GetAcademicGroupInfoResponse_proto_rawDescGZIP(), []int{0, 3}
}

func (x *GetAcademicGroupInfoResponse_Student) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAcademicGroupInfoResponse_Student) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetAcademicGroupInfoResponse_Student) GetVariant() int32 {
	if x != nil {
		return x.Variant
	}
	return 0
}

type GetAcademicGroupInfoResponse_Direction_Code struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAcademicGroupInfoResponse_Direction_Code) Reset() {
	*x = GetAcademicGroupInfoResponse_Direction_Code{}
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcademicGroupInfoResponse_Direction_Code) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcademicGroupInfoResponse_Direction_Code) ProtoMessage() {}

func (x *GetAcademicGroupInfoResponse_Direction_Code) ProtoReflect() protoreflect.Message {
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcademicGroupInfoResponse_Direction_Code.ProtoReflect.Descriptor instead.
func (*GetAcademicGroupInfoResponse_Direction_Code) Descriptor() ([]byte, []int) {
	return file_GetAcademicGroupInfoResponse_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *GetAcademicGroupInfoResponse_Direction_Code) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetAcademicGroupInfoResponse_Student_Fullname struct {
	state         protoimpl.MessageState                                    `protogen:"open.v1"`
	Uuid          string                                                    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                                                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LastName      string                                                    `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	SecondName    *GetAcademicGroupInfoResponse_Student_Fullname_SecondName `protobuf:"bytes,4,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAcademicGroupInfoResponse_Student_Fullname) Reset() {
	*x = GetAcademicGroupInfoResponse_Student_Fullname{}
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcademicGroupInfoResponse_Student_Fullname) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcademicGroupInfoResponse_Student_Fullname) ProtoMessage() {}

func (x *GetAcademicGroupInfoResponse_Student_Fullname) ProtoReflect() protoreflect.Message {
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcademicGroupInfoResponse_Student_Fullname.ProtoReflect.Descriptor instead.
func (*GetAcademicGroupInfoResponse_Student_Fullname) Descriptor() ([]byte, []int) {
	return file_GetAcademicGroupInfoResponse_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *GetAcademicGroupInfoResponse_Student_Fullname) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAcademicGroupInfoResponse_Student_Fullname) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAcademicGroupInfoResponse_Student_Fullname) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetAcademicGroupInfoResponse_Student_Fullname) GetSecondName() *GetAcademicGroupInfoResponse_Student_Fullname_SecondName {
	if x != nil {
		return x.SecondName
	}
	return nil
}

type GetAcademicGroupInfoResponse_Student_Fullname_SecondName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAcademicGroupInfoResponse_Student_Fullname_SecondName) Reset() {
	*x = GetAcademicGroupInfoResponse_Student_Fullname_SecondName{}
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcademicGroupInfoResponse_Student_Fullname_SecondName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcademicGroupInfoResponse_Student_Fullname_SecondName) ProtoMessage() {}

func (x *GetAcademicGroupInfoResponse_Student_Fullname_SecondName) ProtoReflect() protoreflect.Message {
	mi := &file_GetAcademicGroupInfoResponse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcademicGroupInfoResponse_Student_Fullname_SecondName.ProtoReflect.Descriptor instead.
func (*GetAcademicGroupInfoResponse_Student_Fullname_SecondName) Descriptor() ([]byte, []int) {
	return file_GetAcademicGroupInfoResponse_proto_rawDescGZIP(), []int{0, 3, 0, 0}
}

func (x *GetAcademicGroupInfoResponse_Student_Fullname_SecondName) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_GetAcademicGroupInfoResponse_proto protoreflect.FileDescriptor

const file_GetAcademicGroupInfoResponse_proto_rawDesc = "" +
	"\n" +
	"\"GetAcademicGroupInfoResponse.proto\x12\amessage\"\xa4\a\n" +
	"\x1cGetAcademicGroupInfoResponse\x12B\n" +
	"\x04uuid\x18\x03 \x01(\v2..message.GetAcademicGroupInfoResponse.UuidInfoR\x04uuid\x12M\n" +
	"\tdirection\x18\x05 \x01(\v2/.message.GetAcademicGroupInfoResponse.DirectionR\tdirection\x12N\n" +
	"\tdeparment\x18\x06 \x01(\v20.message.GetAcademicGroupInfoResponse.DepartmentR\tdeparment\x12I\n" +
	"\bstudents\x18\a \x03(\v2-.message.GetAcademicGroupInfoResponse.StudentR\bstudents\x1a8\n" +
	"\bUuidInfo\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\avariant\x18\x02 \x01(\x05R\avariant\x1a\x9d\x01\n" +
	"\tDirection\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12H\n" +
	"\x04code\x18\x03 \x01(\v24.message.GetAcademicGroupInfoResponse.Direction.CodeR\x04code\x1a\x1c\n" +
	"\x04Code\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x1aT\n" +
	"\n" +
	"Department\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1e\n" +
	"\n" +
	"department\x18\x02 \x01(\tR\n" +
	"department\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x1a\xa5\x02\n" +
	"\aStudent\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\avariant\x18\x03 \x01(\x05R\avariant\x1a\xd7\x01\n" +
	"\bFullname\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12b\n" +
	"\vsecond_name\x18\x04 \x01(\v2A.message.GetAcademicGroupInfoResponse.Student.Fullname.SecondNameR\n" +
	"secondName\x1a\"\n" +
	"\n" +
	"SecondName\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB\x11Z\x0f./proto;messageb\x06proto3"

var (
	file_GetAcademicGroupInfoResponse_proto_rawDescOnce sync.Once
	file_GetAcademicGroupInfoResponse_proto_rawDescData []byte
)

func file_GetAcademicGroupInfoResponse_proto_rawDescGZIP() []byte {
	file_GetAcademicGroupInfoResponse_proto_rawDescOnce.Do(func() {
		file_GetAcademicGroupInfoResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetAcademicGroupInfoResponse_proto_rawDesc), len(file_GetAcademicGroupInfoResponse_proto_rawDesc)))
	})
	return file_GetAcademicGroupInfoResponse_proto_rawDescData
}

var file_GetAcademicGroupInfoResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_GetAcademicGroupInfoResponse_proto_goTypes = []any{
	(*GetAcademicGroupInfoResponse)(nil),                             // 0: message.GetAcademicGroupInfoResponse
	(*GetAcademicGroupInfoResponse_UuidInfo)(nil),                    // 1: message.GetAcademicGroupInfoResponse.UuidInfo
	(*GetAcademicGroupInfoResponse_Direction)(nil),                   // 2: message.GetAcademicGroupInfoResponse.Direction
	(*GetAcademicGroupInfoResponse_Department)(nil),                  // 3: message.GetAcademicGroupInfoResponse.Department
	(*GetAcademicGroupInfoResponse_Student)(nil),                     // 4: message.GetAcademicGroupInfoResponse.Student
	(*GetAcademicGroupInfoResponse_Direction_Code)(nil),              // 5: message.GetAcademicGroupInfoResponse.Direction.Code
	(*GetAcademicGroupInfoResponse_Student_Fullname)(nil),            // 6: message.GetAcademicGroupInfoResponse.Student.Fullname
	(*GetAcademicGroupInfoResponse_Student_Fullname_SecondName)(nil), // 7: message.GetAcademicGroupInfoResponse.Student.Fullname.SecondName
}
var file_GetAcademicGroupInfoResponse_proto_depIdxs = []int32{
	1, // 0: message.GetAcademicGroupInfoResponse.uuid:type_name -> message.GetAcademicGroupInfoResponse.UuidInfo
	2, // 1: message.GetAcademicGroupInfoResponse.direction:type_name -> message.GetAcademicGroupInfoResponse.Direction
	3, // 2: message.GetAcademicGroupInfoResponse.deparment:type_name -> message.GetAcademicGroupInfoResponse.Department
	4, // 3: message.GetAcademicGroupInfoResponse.students:type_name -> message.GetAcademicGroupInfoResponse.Student
	5, // 4: message.GetAcademicGroupInfoResponse.Direction.code:type_name -> message.GetAcademicGroupInfoResponse.Direction.Code
	7, // 5: message.GetAcademicGroupInfoResponse.Student.Fullname.second_name:type_name -> message.GetAcademicGroupInfoResponse.Student.Fullname.SecondName
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_GetAcademicGroupInfoResponse_proto_init() }
func file_GetAcademicGroupInfoResponse_proto_init() {
	if File_GetAcademicGroupInfoResponse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetAcademicGroupInfoResponse_proto_rawDesc), len(file_GetAcademicGroupInfoResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetAcademicGroupInfoResponse_proto_goTypes,
		DependencyIndexes: file_GetAcademicGroupInfoResponse_proto_depIdxs,
		MessageInfos:      file_GetAcademicGroupInfoResponse_proto_msgTypes,
	}.Build()
	File_GetAcademicGroupInfoResponse_proto = out.File
	file_GetAcademicGroupInfoResponse_proto_goTypes = nil
	file_GetAcademicGroupInfoResponse_proto_depIdxs = nil
}
