// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: GetAcademicGroupInfoRequest.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAcademicGroupInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAcademicGroupInfoRequest) Reset() {
	*x = GetAcademicGroupInfoRequest{}
	mi := &file_GetAcademicGroupInfoRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcademicGroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcademicGroupInfoRequest) ProtoMessage() {}

func (x *GetAcademicGroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GetAcademicGroupInfoRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcademicGroupInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAcademicGroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_GetAcademicGroupInfoRequest_proto_rawDescGZIP(), []int{0}
}

func (x *GetAcademicGroupInfoRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_GetAcademicGroupInfoRequest_proto protoreflect.FileDescriptor

const file_GetAcademicGroupInfoRequest_proto_rawDesc = "" +
	"\n" +
	"!GetAcademicGroupInfoRequest.proto\x12\amessage\"1\n" +
	"\x1bGetAcademicGroupInfoRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuidB\x11Z\x0f./proto;messageb\x06proto3"

var (
	file_GetAcademicGroupInfoRequest_proto_rawDescOnce sync.Once
	file_GetAcademicGroupInfoRequest_proto_rawDescData []byte
)

func file_GetAcademicGroupInfoRequest_proto_rawDescGZIP() []byte {
	file_GetAcademicGroupInfoRequest_proto_rawDescOnce.Do(func() {
		file_GetAcademicGroupInfoRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetAcademicGroupInfoRequest_proto_rawDesc), len(file_GetAcademicGroupInfoRequest_proto_rawDesc)))
	})
	return file_GetAcademicGroupInfoRequest_proto_rawDescData
}

var file_GetAcademicGroupInfoRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GetAcademicGroupInfoRequest_proto_goTypes = []any{
	(*GetAcademicGroupInfoRequest)(nil), // 0: message.GetAcademicGroupInfoRequest
}
var file_GetAcademicGroupInfoRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GetAcademicGroupInfoRequest_proto_init() }
func file_GetAcademicGroupInfoRequest_proto_init() {
	if File_GetAcademicGroupInfoRequest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetAcademicGroupInfoRequest_proto_rawDesc), len(file_GetAcademicGroupInfoRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetAcademicGroupInfoRequest_proto_goTypes,
		DependencyIndexes: file_GetAcademicGroupInfoRequest_proto_depIdxs,
		MessageInfos:      file_GetAcademicGroupInfoRequest_proto_msgTypes,
	}.Build()
	File_GetAcademicGroupInfoRequest_proto = out.File
	file_GetAcademicGroupInfoRequest_proto_goTypes = nil
	file_GetAcademicGroupInfoRequest_proto_depIdxs = nil
}
