// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: GetAvailableLessonsOfVisitingLogsRequest.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAvailableLessonsOfVisitingLogsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VisitingLogIds string                 `protobuf:"bytes,1,opt,name=visiting_log_ids,json=visitingLogIds,proto3" json:"visiting_log_ids,omitempty"`
	Date           *DateInfo              `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAvailableLessonsOfVisitingLogsRequest) Reset() {
	*x = GetAvailableLessonsOfVisitingLogsRequest{}
	mi := &file_GetAvailableLessonsOfVisitingLogsRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableLessonsOfVisitingLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableLessonsOfVisitingLogsRequest) ProtoMessage() {}

func (x *GetAvailableLessonsOfVisitingLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableLessonsOfVisitingLogsRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableLessonsOfVisitingLogsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableLessonsOfVisitingLogsRequest) Descriptor() ([]byte, []int) {
	return file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDescGZIP(), []int{0}
}

func (x *GetAvailableLessonsOfVisitingLogsRequest) GetVisitingLogIds() string {
	if x != nil {
		return x.VisitingLogIds
	}
	return ""
}

func (x *GetAvailableLessonsOfVisitingLogsRequest) GetDate() *DateInfo {
	if x != nil {
		return x.Date
	}
	return nil
}

type DateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day           int32                  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateInfo) Reset() {
	*x = DateInfo{}
	mi := &file_GetAvailableLessonsOfVisitingLogsRequest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateInfo) ProtoMessage() {}

func (x *DateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GetAvailableLessonsOfVisitingLogsRequest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateInfo.ProtoReflect.Descriptor instead.
func (*DateInfo) Descriptor() ([]byte, []int) {
	return file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDescGZIP(), []int{1}
}

func (x *DateInfo) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *DateInfo) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *DateInfo) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

var File_GetAvailableLessonsOfVisitingLogsRequest_proto protoreflect.FileDescriptor

const file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDesc = "" +
	"\n" +
	".GetAvailableLessonsOfVisitingLogsRequest.proto\x12\amessage\"{\n" +
	"(GetAvailableLessonsOfVisitingLogsRequest\x12(\n" +
	"\x10visiting_log_ids\x18\x01 \x01(\tR\x0evisitingLogIds\x12%\n" +
	"\x04date\x18\x02 \x01(\v2\x11.message.DateInfoR\x04date\"F\n" +
	"\bDateInfo\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x05R\x03dayB\x11Z\x0f./proto;messageb\x06proto3"

var (
	file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDescOnce sync.Once
	file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDescData []byte
)

func file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDescGZIP() []byte {
	file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDescOnce.Do(func() {
		file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDesc), len(file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDesc)))
	})
	return file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDescData
}

var file_GetAvailableLessonsOfVisitingLogsRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetAvailableLessonsOfVisitingLogsRequest_proto_goTypes = []any{
	(*GetAvailableLessonsOfVisitingLogsRequest)(nil), // 0: message.GetAvailableLessonsOfVisitingLogsRequest
	(*DateInfo)(nil), // 1: message.DateInfo
}
var file_GetAvailableLessonsOfVisitingLogsRequest_proto_depIdxs = []int32{
	1, // 0: message.GetAvailableLessonsOfVisitingLogsRequest.date:type_name -> message.DateInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_GetAvailableLessonsOfVisitingLogsRequest_proto_init() }
func file_GetAvailableLessonsOfVisitingLogsRequest_proto_init() {
	if File_GetAvailableLessonsOfVisitingLogsRequest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDesc), len(file_GetAvailableLessonsOfVisitingLogsRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetAvailableLessonsOfVisitingLogsRequest_proto_goTypes,
		DependencyIndexes: file_GetAvailableLessonsOfVisitingLogsRequest_proto_depIdxs,
		MessageInfos:      file_GetAvailableLessonsOfVisitingLogsRequest_proto_msgTypes,
	}.Build()
	File_GetAvailableLessonsOfVisitingLogsRequest_proto = out.File
	file_GetAvailableLessonsOfVisitingLogsRequest_proto_goTypes = nil
	file_GetAvailableLessonsOfVisitingLogsRequest_proto_depIdxs = nil
}
