// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: GetAttendanceForLessonRequest.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAttendanceForLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lessonId,proto3" json:"lessonId,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttendanceForLessonRequest) Reset() {
	*x = GetAttendanceForLessonRequest{}
	mi := &file_GetAttendanceForLessonRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttendanceForLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendanceForLessonRequest) ProtoMessage() {}

func (x *GetAttendanceForLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GetAttendanceForLessonRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendanceForLessonRequest.ProtoReflect.Descriptor instead.
func (*GetAttendanceForLessonRequest) Descriptor() ([]byte, []int) {
	return file_GetAttendanceForLessonRequest_proto_rawDescGZIP(), []int{0}
}

func (x *GetAttendanceForLessonRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *GetAttendanceForLessonRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

var File_GetAttendanceForLessonRequest_proto protoreflect.FileDescriptor

const file_GetAttendanceForLessonRequest_proto_rawDesc = "" +
	"\n" +
	"#GetAttendanceForLessonRequest.proto\x12\amessage\"U\n" +
	"\x1dGetAttendanceForLessonRequest\x12\x1a\n" +
	"\blessonId\x18\x01 \x01(\tR\blessonId\x12\x18\n" +
	"\agroupId\x18\x02 \x01(\tR\agroupIdB\x11Z\x0f./proto;messageb\x06proto3"

var (
	file_GetAttendanceForLessonRequest_proto_rawDescOnce sync.Once
	file_GetAttendanceForLessonRequest_proto_rawDescData []byte
)

func file_GetAttendanceForLessonRequest_proto_rawDescGZIP() []byte {
	file_GetAttendanceForLessonRequest_proto_rawDescOnce.Do(func() {
		file_GetAttendanceForLessonRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetAttendanceForLessonRequest_proto_rawDesc), len(file_GetAttendanceForLessonRequest_proto_rawDesc)))
	})
	return file_GetAttendanceForLessonRequest_proto_rawDescData
}

var file_GetAttendanceForLessonRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GetAttendanceForLessonRequest_proto_goTypes = []any{
	(*GetAttendanceForLessonRequest)(nil), // 0: message.GetAttendanceForLessonRequest
}
var file_GetAttendanceForLessonRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GetAttendanceForLessonRequest_proto_init() }
func file_GetAttendanceForLessonRequest_proto_init() {
	if File_GetAttendanceForLessonRequest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetAttendanceForLessonRequest_proto_rawDesc), len(file_GetAttendanceForLessonRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetAttendanceForLessonRequest_proto_goTypes,
		DependencyIndexes: file_GetAttendanceForLessonRequest_proto_depIdxs,
		MessageInfos:      file_GetAttendanceForLessonRequest_proto_msgTypes,
	}.Build()
	File_GetAttendanceForLessonRequest_proto = out.File
	file_GetAttendanceForLessonRequest_proto_goTypes = nil
	file_GetAttendanceForLessonRequest_proto_depIdxs = nil
}
