// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: GetHumanAcsEventsRequest.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHumanAcsEventsRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	StudentId     string                              `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	TimeRange     *GetHumanAcsEventsRequest_TimeRange `protobuf:"bytes,2,opt,name=timeRange,proto3" json:"timeRange,omitempty"`
	Huinya1       int32                               `protobuf:"varint,3,opt,name=huinya1,proto3" json:"huinya1,omitempty"`
	Huinya2       int32                               `protobuf:"varint,5,opt,name=huinya2,proto3" json:"huinya2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHumanAcsEventsRequest) Reset() {
	*x = GetHumanAcsEventsRequest{}
	mi := &file_GetHumanAcsEventsRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHumanAcsEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHumanAcsEventsRequest) ProtoMessage() {}

func (x *GetHumanAcsEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GetHumanAcsEventsRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHumanAcsEventsRequest.ProtoReflect.Descriptor instead.
func (*GetHumanAcsEventsRequest) Descriptor() ([]byte, []int) {
	return file_GetHumanAcsEventsRequest_proto_rawDescGZIP(), []int{0}
}

func (x *GetHumanAcsEventsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetHumanAcsEventsRequest) GetTimeRange() *GetHumanAcsEventsRequest_TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *GetHumanAcsEventsRequest) GetHuinya1() int32 {
	if x != nil {
		return x.Huinya1
	}
	return 0
}

func (x *GetHumanAcsEventsRequest) GetHuinya2() int32 {
	if x != nil {
		return x.Huinya2
	}
	return 0
}

type GetHumanAcsEventsRequest_Time struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHumanAcsEventsRequest_Time) Reset() {
	*x = GetHumanAcsEventsRequest_Time{}
	mi := &file_GetHumanAcsEventsRequest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHumanAcsEventsRequest_Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHumanAcsEventsRequest_Time) ProtoMessage() {}

func (x *GetHumanAcsEventsRequest_Time) ProtoReflect() protoreflect.Message {
	mi := &file_GetHumanAcsEventsRequest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHumanAcsEventsRequest_Time.ProtoReflect.Descriptor instead.
func (*GetHumanAcsEventsRequest_Time) Descriptor() ([]byte, []int) {
	return file_GetHumanAcsEventsRequest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetHumanAcsEventsRequest_Time) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetHumanAcsEventsRequest_TimeTwo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	MegaHuinya    int64                  `protobuf:"varint,2,opt,name=megaHuinya,proto3" json:"megaHuinya,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHumanAcsEventsRequest_TimeTwo) Reset() {
	*x = GetHumanAcsEventsRequest_TimeTwo{}
	mi := &file_GetHumanAcsEventsRequest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHumanAcsEventsRequest_TimeTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHumanAcsEventsRequest_TimeTwo) ProtoMessage() {}

func (x *GetHumanAcsEventsRequest_TimeTwo) ProtoReflect() protoreflect.Message {
	mi := &file_GetHumanAcsEventsRequest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHumanAcsEventsRequest_TimeTwo.ProtoReflect.Descriptor instead.
func (*GetHumanAcsEventsRequest_TimeTwo) Descriptor() ([]byte, []int) {
	return file_GetHumanAcsEventsRequest_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetHumanAcsEventsRequest_TimeTwo) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GetHumanAcsEventsRequest_TimeTwo) GetMegaHuinya() int64 {
	if x != nil {
		return x.MegaHuinya
	}
	return 0
}

type GetHumanAcsEventsRequest_TimeRange struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	StartTime     *GetHumanAcsEventsRequest_Time    `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       *GetHumanAcsEventsRequest_TimeTwo `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHumanAcsEventsRequest_TimeRange) Reset() {
	*x = GetHumanAcsEventsRequest_TimeRange{}
	mi := &file_GetHumanAcsEventsRequest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHumanAcsEventsRequest_TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHumanAcsEventsRequest_TimeRange) ProtoMessage() {}

func (x *GetHumanAcsEventsRequest_TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_GetHumanAcsEventsRequest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHumanAcsEventsRequest_TimeRange.ProtoReflect.Descriptor instead.
func (*GetHumanAcsEventsRequest_TimeRange) Descriptor() ([]byte, []int) {
	return file_GetHumanAcsEventsRequest_proto_rawDescGZIP(), []int{0, 2}
}

func (x *GetHumanAcsEventsRequest_TimeRange) GetStartTime() *GetHumanAcsEventsRequest_Time {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetHumanAcsEventsRequest_TimeRange) GetEndTime() *GetHumanAcsEventsRequest_TimeTwo {
	if x != nil {
		return x.EndTime
	}
	return nil
}

var File_GetHumanAcsEventsRequest_proto protoreflect.FileDescriptor

const file_GetHumanAcsEventsRequest_proto_rawDesc = "" +
	"\n" +
	"\x1eGetHumanAcsEventsRequest.proto\x12\amessage\"\xaf\x03\n" +
	"\x18GetHumanAcsEventsRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12I\n" +
	"\ttimeRange\x18\x02 \x01(\v2+.message.GetHumanAcsEventsRequest.TimeRangeR\ttimeRange\x12\x18\n" +
	"\ahuinya1\x18\x03 \x01(\x05R\ahuinya1\x12\x18\n" +
	"\ahuinya2\x18\x05 \x01(\x05R\ahuinya2\x1a\x1c\n" +
	"\x04Time\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x1a?\n" +
	"\aTimeTwo\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x1e\n" +
	"\n" +
	"megaHuinya\x18\x02 \x01(\x03R\n" +
	"megaHuinya\x1a\x96\x01\n" +
	"\tTimeRange\x12D\n" +
	"\tstartTime\x18\x01 \x01(\v2&.message.GetHumanAcsEventsRequest.TimeR\tstartTime\x12C\n" +
	"\aendTime\x18\x02 \x01(\v2).message.GetHumanAcsEventsRequest.TimeTwoR\aendTimeB\x11Z\x0f./proto;messageb\x06proto3"

var (
	file_GetHumanAcsEventsRequest_proto_rawDescOnce sync.Once
	file_GetHumanAcsEventsRequest_proto_rawDescData []byte
)

func file_GetHumanAcsEventsRequest_proto_rawDescGZIP() []byte {
	file_GetHumanAcsEventsRequest_proto_rawDescOnce.Do(func() {
		file_GetHumanAcsEventsRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetHumanAcsEventsRequest_proto_rawDesc), len(file_GetHumanAcsEventsRequest_proto_rawDesc)))
	})
	return file_GetHumanAcsEventsRequest_proto_rawDescData
}

var file_GetHumanAcsEventsRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_GetHumanAcsEventsRequest_proto_goTypes = []any{
	(*GetHumanAcsEventsRequest)(nil),           // 0: message.GetHumanAcsEventsRequest
	(*GetHumanAcsEventsRequest_Time)(nil),      // 1: message.GetHumanAcsEventsRequest.Time
	(*GetHumanAcsEventsRequest_TimeTwo)(nil),   // 2: message.GetHumanAcsEventsRequest.TimeTwo
	(*GetHumanAcsEventsRequest_TimeRange)(nil), // 3: message.GetHumanAcsEventsRequest.TimeRange
}
var file_GetHumanAcsEventsRequest_proto_depIdxs = []int32{
	3, // 0: message.GetHumanAcsEventsRequest.timeRange:type_name -> message.GetHumanAcsEventsRequest.TimeRange
	1, // 1: message.GetHumanAcsEventsRequest.TimeRange.startTime:type_name -> message.GetHumanAcsEventsRequest.Time
	2, // 2: message.GetHumanAcsEventsRequest.TimeRange.endTime:type_name -> message.GetHumanAcsEventsRequest.TimeTwo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_GetHumanAcsEventsRequest_proto_init() }
func file_GetHumanAcsEventsRequest_proto_init() {
	if File_GetHumanAcsEventsRequest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetHumanAcsEventsRequest_proto_rawDesc), len(file_GetHumanAcsEventsRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetHumanAcsEventsRequest_proto_goTypes,
		DependencyIndexes: file_GetHumanAcsEventsRequest_proto_depIdxs,
		MessageInfos:      file_GetHumanAcsEventsRequest_proto_msgTypes,
	}.Build()
	File_GetHumanAcsEventsRequest_proto = out.File
	file_GetHumanAcsEventsRequest_proto_goTypes = nil
	file_GetHumanAcsEventsRequest_proto_depIdxs = nil
}
