// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: GetHumanAcsEventsResponse.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHumanAcsEventsResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Info          []*GetHumanAcsEventsResponse_Info `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHumanAcsEventsResponse) Reset() {
	*x = GetHumanAcsEventsResponse{}
	mi := &file_GetHumanAcsEventsResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHumanAcsEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHumanAcsEventsResponse) ProtoMessage() {}

func (x *GetHumanAcsEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GetHumanAcsEventsResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHumanAcsEventsResponse.ProtoReflect.Descriptor instead.
func (*GetHumanAcsEventsResponse) Descriptor() ([]byte, []int) {
	return file_GetHumanAcsEventsResponse_proto_rawDescGZIP(), []int{0}
}

func (x *GetHumanAcsEventsResponse) GetInfo() []*GetHumanAcsEventsResponse_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetHumanAcsEventsResponse_Info struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Uuid          string                                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Time          *GetHumanAcsEventsResponse_Info_Time     `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	EntryLocation *GetHumanAcsEventsResponse_Info_Location `protobuf:"bytes,3,opt,name=entryLocation,proto3" json:"entryLocation,omitempty"`
	ExitLocation  *GetHumanAcsEventsResponse_Info_Location `protobuf:"bytes,4,opt,name=exitLocation,proto3" json:"exitLocation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHumanAcsEventsResponse_Info) Reset() {
	*x = GetHumanAcsEventsResponse_Info{}
	mi := &file_GetHumanAcsEventsResponse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHumanAcsEventsResponse_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHumanAcsEventsResponse_Info) ProtoMessage() {}

func (x *GetHumanAcsEventsResponse_Info) ProtoReflect() protoreflect.Message {
	mi := &file_GetHumanAcsEventsResponse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHumanAcsEventsResponse_Info.ProtoReflect.Descriptor instead.
func (*GetHumanAcsEventsResponse_Info) Descriptor() ([]byte, []int) {
	return file_GetHumanAcsEventsResponse_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetHumanAcsEventsResponse_Info) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetHumanAcsEventsResponse_Info) GetTime() *GetHumanAcsEventsResponse_Info_Time {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GetHumanAcsEventsResponse_Info) GetEntryLocation() *GetHumanAcsEventsResponse_Info_Location {
	if x != nil {
		return x.EntryLocation
	}
	return nil
}

func (x *GetHumanAcsEventsResponse_Info) GetExitLocation() *GetHumanAcsEventsResponse_Info_Location {
	if x != nil {
		return x.ExitLocation
	}
	return nil
}

type GetHumanAcsEventsResponse_Info_Time struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHumanAcsEventsResponse_Info_Time) Reset() {
	*x = GetHumanAcsEventsResponse_Info_Time{}
	mi := &file_GetHumanAcsEventsResponse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHumanAcsEventsResponse_Info_Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHumanAcsEventsResponse_Info_Time) ProtoMessage() {}

func (x *GetHumanAcsEventsResponse_Info_Time) ProtoReflect() protoreflect.Message {
	mi := &file_GetHumanAcsEventsResponse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHumanAcsEventsResponse_Info_Time.ProtoReflect.Descriptor instead.
func (*GetHumanAcsEventsResponse_Info_Time) Descriptor() ([]byte, []int) {
	return file_GetHumanAcsEventsResponse_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GetHumanAcsEventsResponse_Info_Time) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetHumanAcsEventsResponse_Info_Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHumanAcsEventsResponse_Info_Location) Reset() {
	*x = GetHumanAcsEventsResponse_Info_Location{}
	mi := &file_GetHumanAcsEventsResponse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHumanAcsEventsResponse_Info_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHumanAcsEventsResponse_Info_Location) ProtoMessage() {}

func (x *GetHumanAcsEventsResponse_Info_Location) ProtoReflect() protoreflect.Message {
	mi := &file_GetHumanAcsEventsResponse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHumanAcsEventsResponse_Info_Location.ProtoReflect.Descriptor instead.
func (*GetHumanAcsEventsResponse_Info_Location) Descriptor() ([]byte, []int) {
	return file_GetHumanAcsEventsResponse_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *GetHumanAcsEventsResponse_Info_Location) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetHumanAcsEventsResponse_Info_Location) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_GetHumanAcsEventsResponse_proto protoreflect.FileDescriptor

const file_GetHumanAcsEventsResponse_proto_rawDesc = "" +
	"\n" +
	"\x1fGetHumanAcsEventsResponse.proto\x12\amessage\"\xb9\x03\n" +
	"\x19GetHumanAcsEventsResponse\x12;\n" +
	"\x04info\x18\x01 \x03(\v2'.message.GetHumanAcsEventsResponse.InfoR\x04info\x1a\xde\x02\n" +
	"\x04Info\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12@\n" +
	"\x04time\x18\x02 \x01(\v2,.message.GetHumanAcsEventsResponse.Info.TimeR\x04time\x12V\n" +
	"\rentryLocation\x18\x03 \x01(\v20.message.GetHumanAcsEventsResponse.Info.LocationR\rentryLocation\x12T\n" +
	"\fexitLocation\x18\x04 \x01(\v20.message.GetHumanAcsEventsResponse.Info.LocationR\fexitLocation\x1a\x1c\n" +
	"\x04Time\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x1a4\n" +
	"\bLocation\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05titleB\x11Z\x0f./proto;messageb\x06proto3"

var (
	file_GetHumanAcsEventsResponse_proto_rawDescOnce sync.Once
	file_GetHumanAcsEventsResponse_proto_rawDescData []byte
)

func file_GetHumanAcsEventsResponse_proto_rawDescGZIP() []byte {
	file_GetHumanAcsEventsResponse_proto_rawDescOnce.Do(func() {
		file_GetHumanAcsEventsResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetHumanAcsEventsResponse_proto_rawDesc), len(file_GetHumanAcsEventsResponse_proto_rawDesc)))
	})
	return file_GetHumanAcsEventsResponse_proto_rawDescData
}

var file_GetHumanAcsEventsResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_GetHumanAcsEventsResponse_proto_goTypes = []any{
	(*GetHumanAcsEventsResponse)(nil),               // 0: message.GetHumanAcsEventsResponse
	(*GetHumanAcsEventsResponse_Info)(nil),          // 1: message.GetHumanAcsEventsResponse.Info
	(*GetHumanAcsEventsResponse_Info_Time)(nil),     // 2: message.GetHumanAcsEventsResponse.Info.Time
	(*GetHumanAcsEventsResponse_Info_Location)(nil), // 3: message.GetHumanAcsEventsResponse.Info.Location
}
var file_GetHumanAcsEventsResponse_proto_depIdxs = []int32{
	1, // 0: message.GetHumanAcsEventsResponse.info:type_name -> message.GetHumanAcsEventsResponse.Info
	2, // 1: message.GetHumanAcsEventsResponse.Info.time:type_name -> message.GetHumanAcsEventsResponse.Info.Time
	3, // 2: message.GetHumanAcsEventsResponse.Info.entryLocation:type_name -> message.GetHumanAcsEventsResponse.Info.Location
	3, // 3: message.GetHumanAcsEventsResponse.Info.exitLocation:type_name -> message.GetHumanAcsEventsResponse.Info.Location
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_GetHumanAcsEventsResponse_proto_init() }
func file_GetHumanAcsEventsResponse_proto_init() {
	if File_GetHumanAcsEventsResponse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetHumanAcsEventsResponse_proto_rawDesc), len(file_GetHumanAcsEventsResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetHumanAcsEventsResponse_proto_goTypes,
		DependencyIndexes: file_GetHumanAcsEventsResponse_proto_depIdxs,
		MessageInfos:      file_GetHumanAcsEventsResponse_proto_msgTypes,
	}.Build()
	File_GetHumanAcsEventsResponse_proto = out.File
	file_GetHumanAcsEventsResponse_proto_goTypes = nil
	file_GetHumanAcsEventsResponse_proto_depIdxs = nil
}
