// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: GetLearnRatingScoreResponse.proto

package message

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLearnRatingScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLearnRatingScoreResponse) Reset() {
	*x = GetLearnRatingScoreResponse{}
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLearnRatingScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLearnRatingScoreResponse) ProtoMessage() {}

func (x *GetLearnRatingScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLearnRatingScoreResponse.ProtoReflect.Descriptor instead.
func (*GetLearnRatingScoreResponse) Descriptor() ([]byte, []int) {
	return file_GetLearnRatingScoreResponse_proto_rawDescGZIP(), []int{0}
}

func (x *GetLearnRatingScoreResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Discipline    []*Info                `protobuf:"bytes,1,rep,name=discipline,proto3" json:"discipline,omitempty"`
	ValueData     []*Response_ValueData  `protobuf:"bytes,2,rep,name=value_data,json=valueData,proto3" json:"value_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_GetLearnRatingScoreResponse_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetDiscipline() []*Info {
	if x != nil {
		return x.Discipline
	}
	return nil
}

func (x *Response) GetValueData() []*Response_ValueData {
	if x != nil {
		return x.ValueData
	}
	return nil
}

type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *Title                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ScoreData     []*ScoreData           `protobuf:"bytes,2,rep,name=score_data,json=scoreData,proto3" json:"score_data,omitempty"`
	Total         float64                `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_GetLearnRatingScoreResponse_proto_rawDescGZIP(), []int{2}
}

func (x *Info) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Info) GetScoreData() []*ScoreData {
	if x != nil {
		return x.ScoreData
	}
	return nil
}

func (x *Info) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Title struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_GetLearnRatingScoreResponse_proto_rawDescGZIP(), []int{3}
}

func (x *Title) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ScoreData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Now           float64                `protobuf:"fixed64,2,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreData) Reset() {
	*x = ScoreData{}
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreData) ProtoMessage() {}

func (x *ScoreData) ProtoReflect() protoreflect.Message {
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreData.ProtoReflect.Descriptor instead.
func (*ScoreData) Descriptor() ([]byte, []int) {
	return file_GetLearnRatingScoreResponse_proto_rawDescGZIP(), []int{4}
}

func (x *ScoreData) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ScoreData) GetNow() float64 {
	if x != nil {
		return x.Now
	}
	return 0
}

type Response_ValueData struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Variant       int32                       `protobuf:"varint,1,opt,name=variant,proto3" json:"variant,omitempty"`
	Block         []*Response_ValueData_Block `protobuf:"bytes,2,rep,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response_ValueData) Reset() {
	*x = Response_ValueData{}
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response_ValueData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_ValueData) ProtoMessage() {}

func (x *Response_ValueData) ProtoReflect() protoreflect.Message {
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_ValueData.ProtoReflect.Descriptor instead.
func (*Response_ValueData) Descriptor() ([]byte, []int) {
	return file_GetLearnRatingScoreResponse_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Response_ValueData) GetVariant() int32 {
	if x != nil {
		return x.Variant
	}
	return 0
}

func (x *Response_ValueData) GetBlock() []*Response_ValueData_Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type Response_ValueData_Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Max           int32                  `protobuf:"varint,4,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response_ValueData_Block) Reset() {
	*x = Response_ValueData_Block{}
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response_ValueData_Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_ValueData_Block) ProtoMessage() {}

func (x *Response_ValueData_Block) ProtoReflect() protoreflect.Message {
	mi := &file_GetLearnRatingScoreResponse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_ValueData_Block.ProtoReflect.Descriptor instead.
func (*Response_ValueData_Block) Descriptor() ([]byte, []int) {
	return file_GetLearnRatingScoreResponse_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Response_ValueData_Block) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Response_ValueData_Block) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Response_ValueData_Block) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

var File_GetLearnRatingScoreResponse_proto protoreflect.FileDescriptor

const file_GetLearnRatingScoreResponse_proto_rawDesc = "" +
	"\n" +
	"!GetLearnRatingScoreResponse.proto\x12\amessage\"L\n" +
	"\x1bGetLearnRatingScoreResponse\x12-\n" +
	"\bresponse\x18\x01 \x01(\v2\x11.message.ResponseR\bresponse\"\x9b\x02\n" +
	"\bResponse\x12-\n" +
	"\n" +
	"discipline\x18\x01 \x03(\v2\r.message.InfoR\n" +
	"discipline\x12:\n" +
	"\n" +
	"value_data\x18\x02 \x03(\v2\x1b.message.Response.ValueDataR\tvalueData\x1a\xa3\x01\n" +
	"\tValueData\x12\x18\n" +
	"\avariant\x18\x01 \x01(\x05R\avariant\x127\n" +
	"\x05block\x18\x02 \x03(\v2!.message.Response.ValueData.BlockR\x05block\x1aC\n" +
	"\x05Block\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x05R\x03max\"u\n" +
	"\x04Info\x12$\n" +
	"\x05title\x18\x01 \x01(\v2\x0e.message.TitleR\x05title\x121\n" +
	"\n" +
	"score_data\x18\x02 \x03(\v2\x12.message.ScoreDataR\tscoreData\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x01R\x05total\"\x1d\n" +
	"\x05Title\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"1\n" +
	"\tScoreData\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03now\x18\x02 \x01(\x01R\x03nowB\x11Z\x0f./proto;messageb\x06proto3"

var (
	file_GetLearnRatingScoreResponse_proto_rawDescOnce sync.Once
	file_GetLearnRatingScoreResponse_proto_rawDescData []byte
)

func file_GetLearnRatingScoreResponse_proto_rawDescGZIP() []byte {
	file_GetLearnRatingScoreResponse_proto_rawDescOnce.Do(func() {
		file_GetLearnRatingScoreResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetLearnRatingScoreResponse_proto_rawDesc), len(file_GetLearnRatingScoreResponse_proto_rawDesc)))
	})
	return file_GetLearnRatingScoreResponse_proto_rawDescData
}

var file_GetLearnRatingScoreResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_GetLearnRatingScoreResponse_proto_goTypes = []any{
	(*GetLearnRatingScoreResponse)(nil), // 0: message.GetLearnRatingScoreResponse
	(*Response)(nil),                    // 1: message.Response
	(*Info)(nil),                        // 2: message.Info
	(*Title)(nil),                       // 3: message.Title
	(*ScoreData)(nil),                   // 4: message.ScoreData
	(*Response_ValueData)(nil),          // 5: message.Response.ValueData
	(*Response_ValueData_Block)(nil),    // 6: message.Response.ValueData.Block
}
var file_GetLearnRatingScoreResponse_proto_depIdxs = []int32{
	1, // 0: message.GetLearnRatingScoreResponse.response:type_name -> message.Response
	2, // 1: message.Response.discipline:type_name -> message.Info
	5, // 2: message.Response.value_data:type_name -> message.Response.ValueData
	3, // 3: message.Info.title:type_name -> message.Title
	4, // 4: message.Info.score_data:type_name -> message.ScoreData
	6, // 5: message.Response.ValueData.block:type_name -> message.Response.ValueData.Block
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_GetLearnRatingScoreResponse_proto_init() }
func file_GetLearnRatingScoreResponse_proto_init() {
	if File_GetLearnRatingScoreResponse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetLearnRatingScoreResponse_proto_rawDesc), len(file_GetLearnRatingScoreResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetLearnRatingScoreResponse_proto_goTypes,
		DependencyIndexes: file_GetLearnRatingScoreResponse_proto_depIdxs,
		MessageInfos:      file_GetLearnRatingScoreResponse_proto_msgTypes,
	}.Build()
	File_GetLearnRatingScoreResponse_proto = out.File
	file_GetLearnRatingScoreResponse_proto_goTypes = nil
	file_GetLearnRatingScoreResponse_proto_depIdxs = nil
}
