// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.0
// source: GetMeInfoRequest.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeInfoRequest) Reset() {
	*x = GetMeInfoRequest{}
	mi := &file_GetMeInfoRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeInfoRequest) ProtoMessage() {}

func (x *GetMeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GetMeInfoRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMeInfoRequest) Descriptor() ([]byte, []int) {
	return file_GetMeInfoRequest_proto_rawDescGZIP(), []int{0}
}

func (x *GetMeInfoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetMeInfoRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_GetMeInfoRequest_proto protoreflect.FileDescriptor

var file_GetMeInfoRequest_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x3a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x11, 0x5a,
	0x0f, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_GetMeInfoRequest_proto_rawDescOnce sync.Once
	file_GetMeInfoRequest_proto_rawDescData []byte
)

func file_GetMeInfoRequest_proto_rawDescGZIP() []byte {
	file_GetMeInfoRequest_proto_rawDescOnce.Do(func() {
		file_GetMeInfoRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetMeInfoRequest_proto_rawDesc), len(file_GetMeInfoRequest_proto_rawDesc)))
	})
	return file_GetMeInfoRequest_proto_rawDescData
}

var file_GetMeInfoRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GetMeInfoRequest_proto_goTypes = []any{
	(*GetMeInfoRequest)(nil), // 0: message.GetMeInfoRequest
}
var file_GetMeInfoRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GetMeInfoRequest_proto_init() }
func file_GetMeInfoRequest_proto_init() {
	if File_GetMeInfoRequest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetMeInfoRequest_proto_rawDesc), len(file_GetMeInfoRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetMeInfoRequest_proto_goTypes,
		DependencyIndexes: file_GetMeInfoRequest_proto_depIdxs,
		MessageInfos:      file_GetMeInfoRequest_proto_msgTypes,
	}.Build()
	File_GetMeInfoRequest_proto = out.File
	file_GetMeInfoRequest_proto_goTypes = nil
	file_GetMeInfoRequest_proto_depIdxs = nil
}
