// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.0
// source: GetMeInfoResponse.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *Body                  `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeInfoResponse) Reset() {
	*x = GetMeInfoResponse{}
	mi := &file_GetMeInfoResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeInfoResponse) ProtoMessage() {}

func (x *GetMeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GetMeInfoResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetMeInfoResponse) Descriptor() ([]byte, []int) {
	return file_GetMeInfoResponse_proto_rawDescGZIP(), []int{0}
}

func (x *GetMeInfoResponse) GetBody() *Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type Body struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *Student               `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	UrlLogout     string                 `protobuf:"bytes,2,opt,name=urlLogout,proto3" json:"urlLogout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Body) Reset() {
	*x = Body{}
	mi := &file_GetMeInfoResponse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Body) ProtoMessage() {}

func (x *Body) ProtoReflect() protoreflect.Message {
	mi := &file_GetMeInfoResponse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Body.ProtoReflect.Descriptor instead.
func (*Body) Descriptor() ([]byte, []int) {
	return file_GetMeInfoResponse_proto_rawDescGZIP(), []int{1}
}

func (x *Body) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *Body) GetUrlLogout() string {
	if x != nil {
		return x.UrlLogout
	}
	return ""
}

type Student struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fullname      string                 `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Middlename    *Middlename            `protobuf:"bytes,4,opt,name=middlename,proto3" json:"middlename,omitempty"`
	Future        []*FutureFlag          `protobuf:"bytes,5,rep,name=future,proto3" json:"future,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	DebugInfo     *Debug                 `protobuf:"bytes,7,opt,name=debugInfo,proto3" json:"debugInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_GetMeInfoResponse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_GetMeInfoResponse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_GetMeInfoResponse_proto_rawDescGZIP(), []int{2}
}

func (x *Student) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *Student) GetMiddlename() *Middlename {
	if x != nil {
		return x.Middlename
	}
	return nil
}

func (x *Student) GetFuture() []*FutureFlag {
	if x != nil {
		return x.Future
	}
	return nil
}

func (x *Student) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Student) GetDebugInfo() *Debug {
	if x != nil {
		return x.DebugInfo
	}
	return nil
}

type Middlename struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Middlename) Reset() {
	*x = Middlename{}
	mi := &file_GetMeInfoResponse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Middlename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Middlename) ProtoMessage() {}

func (x *Middlename) ProtoReflect() protoreflect.Message {
	mi := &file_GetMeInfoResponse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Middlename.ProtoReflect.Descriptor instead.
func (*Middlename) Descriptor() ([]byte, []int) {
	return file_GetMeInfoResponse_proto_rawDescGZIP(), []int{3}
}

func (x *Middlename) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Debug struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Debug) Reset() {
	*x = Debug{}
	mi := &file_GetMeInfoResponse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Debug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Debug) ProtoMessage() {}

func (x *Debug) ProtoReflect() protoreflect.Message {
	mi := &file_GetMeInfoResponse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Debug.ProtoReflect.Descriptor instead.
func (*Debug) Descriptor() ([]byte, []int) {
	return file_GetMeInfoResponse_proto_rawDescGZIP(), []int{4}
}

func (x *Debug) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FutureFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value1        string                 `protobuf:"bytes,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2        string                 `protobuf:"bytes,2,opt,name=value2,proto3" json:"value2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FutureFlag) Reset() {
	*x = FutureFlag{}
	mi := &file_GetMeInfoResponse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FutureFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FutureFlag) ProtoMessage() {}

func (x *FutureFlag) ProtoReflect() protoreflect.Message {
	mi := &file_GetMeInfoResponse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FutureFlag.ProtoReflect.Descriptor instead.
func (*FutureFlag) Descriptor() ([]byte, []int) {
	return file_GetMeInfoResponse_proto_rawDescGZIP(), []int{5}
}

func (x *FutureFlag) GetValue1() string {
	if x != nil {
		return x.Value1
	}
	return ""
}

func (x *FutureFlag) GetValue2() string {
	if x != nil {
		return x.Value2
	}
	return ""
}

var File_GetMeInfoResponse_proto protoreflect.FileDescriptor

var file_GetMeInfoResponse_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x36, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x50, 0x0a, 0x04, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x75, 0x72, 0x6c, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x75, 0x72, 0x6c, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x22, 0xef, 0x01, 0x0a,
	0x07, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x6d, 0x69, 0x64, 0x64,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x52, 0x0a, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a,
	0x06, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x46, 0x6c,
	0x61, 0x67, 0x52, 0x06, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x2c, 0x0a, 0x09, 0x64, 0x65, 0x62, 0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x65,
	0x62, 0x75, 0x67, 0x52, 0x09, 0x64, 0x65, 0x62, 0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x22,
	0x0a, 0x0a, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x1d, 0x0a, 0x05, 0x44, 0x65, 0x62, 0x75, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x3c, 0x0a, 0x0a, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x42,
	0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_GetMeInfoResponse_proto_rawDescOnce sync.Once
	file_GetMeInfoResponse_proto_rawDescData []byte
)

func file_GetMeInfoResponse_proto_rawDescGZIP() []byte {
	file_GetMeInfoResponse_proto_rawDescOnce.Do(func() {
		file_GetMeInfoResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetMeInfoResponse_proto_rawDesc), len(file_GetMeInfoResponse_proto_rawDesc)))
	})
	return file_GetMeInfoResponse_proto_rawDescData
}

var file_GetMeInfoResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_GetMeInfoResponse_proto_goTypes = []any{
	(*GetMeInfoResponse)(nil), // 0: message.GetMeInfoResponse
	(*Body)(nil),              // 1: message.Body
	(*Student)(nil),           // 2: message.Student
	(*Middlename)(nil),        // 3: message.Middlename
	(*Debug)(nil),             // 4: message.Debug
	(*FutureFlag)(nil),        // 5: message.FutureFlag
}
var file_GetMeInfoResponse_proto_depIdxs = []int32{
	1, // 0: message.GetMeInfoResponse.body:type_name -> message.Body
	2, // 1: message.Body.student:type_name -> message.Student
	3, // 2: message.Student.middlename:type_name -> message.Middlename
	5, // 3: message.Student.future:type_name -> message.FutureFlag
	4, // 4: message.Student.debugInfo:type_name -> message.Debug
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_GetMeInfoResponse_proto_init() }
func file_GetMeInfoResponse_proto_init() {
	if File_GetMeInfoResponse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetMeInfoResponse_proto_rawDesc), len(file_GetMeInfoResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetMeInfoResponse_proto_goTypes,
		DependencyIndexes: file_GetMeInfoResponse_proto_depIdxs,
		MessageInfos:      file_GetMeInfoResponse_proto_msgTypes,
	}.Build()
	File_GetMeInfoResponse_proto = out.File
	file_GetMeInfoResponse_proto_goTypes = nil
	file_GetMeInfoResponse_proto_depIdxs = nil
}
