// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.0
// source: SelfApproveAttendanceResponse.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelfApproveAttendanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Failed        *Failed                `protobuf:"bytes,1,opt,name=failed,proto3" json:"failed,omitempty"`
	Success       *Success               `protobuf:"bytes,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfApproveAttendanceResponse) Reset() {
	*x = SelfApproveAttendanceResponse{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfApproveAttendanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfApproveAttendanceResponse) ProtoMessage() {}

func (x *SelfApproveAttendanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfApproveAttendanceResponse.ProtoReflect.Descriptor instead.
func (*SelfApproveAttendanceResponse) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{0}
}

func (x *SelfApproveAttendanceResponse) GetFailed() *Failed {
	if x != nil {
		return x.Failed
	}
	return nil
}

func (x *SelfApproveAttendanceResponse) GetSuccess() *Success {
	if x != nil {
		return x.Success
	}
	return nil
}

type Failed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         int32                  `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failed) Reset() {
	*x = Failed{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failed) ProtoMessage() {}

func (x *Failed) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failed.ProtoReflect.Descriptor instead.
func (*Failed) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{1}
}

func (x *Failed) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

type Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Campus        *Campus                `protobuf:"bytes,2,opt,name=campus,proto3" json:"campus,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	SubjectType   string                 `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	Xuinya2       *Xuinya2               `protobuf:"bytes,5,opt,name=xuinya2,proto3" json:"xuinya2,omitempty"`
	Xuinya3       *Xuinya2               `protobuf:"bytes,6,opt,name=xuinya3,proto3" json:"xuinya3,omitempty"`
	Xuinya4       *Xuinya3               `protobuf:"bytes,7,opt,name=xuinya4,proto3" json:"xuinya4,omitempty"`
	Teacher       *Teacher               `protobuf:"bytes,9,opt,name=teacher,proto3" json:"teacher,omitempty"`
	Group         []*GroupLecture        `protobuf:"bytes,10,rep,name=group,proto3" json:"group,omitempty"`
	Uuid2         string                 `protobuf:"bytes,13,opt,name=uuid2,proto3" json:"uuid2,omitempty"`
	Xuinya        int32                  `protobuf:"varint,14,opt,name=xuinya,proto3" json:"xuinya,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{2}
}

func (x *Success) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Success) GetCampus() *Campus {
	if x != nil {
		return x.Campus
	}
	return nil
}

func (x *Success) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Success) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *Success) GetXuinya2() *Xuinya2 {
	if x != nil {
		return x.Xuinya2
	}
	return nil
}

func (x *Success) GetXuinya3() *Xuinya2 {
	if x != nil {
		return x.Xuinya3
	}
	return nil
}

func (x *Success) GetXuinya4() *Xuinya3 {
	if x != nil {
		return x.Xuinya4
	}
	return nil
}

func (x *Success) GetTeacher() *Teacher {
	if x != nil {
		return x.Teacher
	}
	return nil
}

func (x *Success) GetGroup() []*GroupLecture {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *Success) GetUuid2() string {
	if x != nil {
		return x.Uuid2
	}
	return ""
}

func (x *Success) GetXuinya() int32 {
	if x != nil {
		return x.Xuinya
	}
	return 0
}

type Campus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Xuiyna        string                 `protobuf:"bytes,2,opt,name=xuiyna,proto3" json:"xuiyna,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campus) Reset() {
	*x = Campus{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campus) ProtoMessage() {}

func (x *Campus) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campus.ProtoReflect.Descriptor instead.
func (*Campus) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{3}
}

func (x *Campus) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Campus) GetXuiyna() string {
	if x != nil {
		return x.Xuiyna
	}
	return ""
}

func (x *Campus) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Xuinya struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zalupa        int32                  `protobuf:"varint,92426,opt,name=zalupa,proto3" json:"zalupa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Xuinya) Reset() {
	*x = Xuinya{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Xuinya) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Xuinya) ProtoMessage() {}

func (x *Xuinya) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Xuinya.ProtoReflect.Descriptor instead.
func (*Xuinya) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{4}
}

func (x *Xuinya) GetZalupa() int32 {
	if x != nil {
		return x.Zalupa
	}
	return 0
}

type Xuinya2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zalupa        int32                  `protobuf:"varint,1,opt,name=zalupa,proto3" json:"zalupa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Xuinya2) Reset() {
	*x = Xuinya2{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Xuinya2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Xuinya2) ProtoMessage() {}

func (x *Xuinya2) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Xuinya2.ProtoReflect.Descriptor instead.
func (*Xuinya2) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{5}
}

func (x *Xuinya2) GetZalupa() int32 {
	if x != nil {
		return x.Zalupa
	}
	return 0
}

type Xuinya3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zalupa1       int32                  `protobuf:"varint,1,opt,name=zalupa1,proto3" json:"zalupa1,omitempty"`
	Zalupa2       int32                  `protobuf:"varint,2,opt,name=zalupa2,proto3" json:"zalupa2,omitempty"`
	Zalupa3       int32                  `protobuf:"varint,3,opt,name=zalupa3,proto3" json:"zalupa3,omitempty"`
	Zalupa4       int32                  `protobuf:"varint,4,opt,name=zalupa4,proto3" json:"zalupa4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Xuinya3) Reset() {
	*x = Xuinya3{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Xuinya3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Xuinya3) ProtoMessage() {}

func (x *Xuinya3) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Xuinya3.ProtoReflect.Descriptor instead.
func (*Xuinya3) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{6}
}

func (x *Xuinya3) GetZalupa1() int32 {
	if x != nil {
		return x.Zalupa1
	}
	return 0
}

func (x *Xuinya3) GetZalupa2() int32 {
	if x != nil {
		return x.Zalupa2
	}
	return 0
}

func (x *Xuinya3) GetZalupa3() int32 {
	if x != nil {
		return x.Zalupa3
	}
	return 0
}

func (x *Xuinya3) GetZalupa4() int32 {
	if x != nil {
		return x.Zalupa4
	}
	return 0
}

type Teacher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FamilyName    string                 `protobuf:"bytes,3,opt,name=familyName,proto3" json:"familyName,omitempty"`
	MiddleName    *MiddlenameTeacher     `protobuf:"bytes,4,opt,name=middleName,proto3" json:"middleName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Teacher) Reset() {
	*x = Teacher{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Teacher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teacher) ProtoMessage() {}

func (x *Teacher) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teacher.ProtoReflect.Descriptor instead.
func (*Teacher) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{7}
}

func (x *Teacher) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Teacher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Teacher) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *Teacher) GetMiddleName() *MiddlenameTeacher {
	if x != nil {
		return x.MiddleName
	}
	return nil
}

type MiddlenameTeacher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlenameTeacher) Reset() {
	*x = MiddlenameTeacher{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlenameTeacher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlenameTeacher) ProtoMessage() {}

func (x *MiddlenameTeacher) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlenameTeacher.ProtoReflect.Descriptor instead.
func (*MiddlenameTeacher) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{8}
}

func (x *MiddlenameTeacher) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GroupLecture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Uuid2         string                 `protobuf:"bytes,4,opt,name=uuid2,proto3" json:"uuid2,omitempty"`
	Xuinya        *Xuinya4               `protobuf:"bytes,5,opt,name=xuinya,proto3" json:"xuinya,omitempty"`
	Semester      *SemesterLecture       `protobuf:"bytes,6,opt,name=semester,proto3" json:"semester,omitempty"`
	Xuinya2       string                 `protobuf:"bytes,8,opt,name=xuinya2,proto3" json:"xuinya2,omitempty"`
	Xuinya3       *Xuinya6               `protobuf:"bytes,9,opt,name=xuinya3,proto3" json:"xuinya3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupLecture) Reset() {
	*x = GroupLecture{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupLecture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupLecture) ProtoMessage() {}

func (x *GroupLecture) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupLecture.ProtoReflect.Descriptor instead.
func (*GroupLecture) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{9}
}

func (x *GroupLecture) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GroupLecture) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GroupLecture) GetUuid2() string {
	if x != nil {
		return x.Uuid2
	}
	return ""
}

func (x *GroupLecture) GetXuinya() *Xuinya4 {
	if x != nil {
		return x.Xuinya
	}
	return nil
}

func (x *GroupLecture) GetSemester() *SemesterLecture {
	if x != nil {
		return x.Semester
	}
	return nil
}

func (x *GroupLecture) GetXuinya2() string {
	if x != nil {
		return x.Xuinya2
	}
	return ""
}

func (x *GroupLecture) GetXuinya3() *Xuinya6 {
	if x != nil {
		return x.Xuinya3
	}
	return nil
}

type Xuinya4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zalupa1       int32                  `protobuf:"varint,1,opt,name=zalupa1,proto3" json:"zalupa1,omitempty"`
	Zalupa2       int32                  `protobuf:"varint,2,opt,name=zalupa2,proto3" json:"zalupa2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Xuinya4) Reset() {
	*x = Xuinya4{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Xuinya4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Xuinya4) ProtoMessage() {}

func (x *Xuinya4) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Xuinya4.ProtoReflect.Descriptor instead.
func (*Xuinya4) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{10}
}

func (x *Xuinya4) GetZalupa1() int32 {
	if x != nil {
		return x.Zalupa1
	}
	return 0
}

func (x *Xuinya4) GetZalupa2() int32 {
	if x != nil {
		return x.Zalupa2
	}
	return 0
}

type SemesterLecture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Xuinya1       *Xuinya5               `protobuf:"bytes,3,opt,name=xuinya1,proto3" json:"xuinya1,omitempty"`
	Xuinya2       *Xuinya5               `protobuf:"bytes,4,opt,name=xuinya2,proto3" json:"xuinya2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemesterLecture) Reset() {
	*x = SemesterLecture{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemesterLecture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemesterLecture) ProtoMessage() {}

func (x *SemesterLecture) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemesterLecture.ProtoReflect.Descriptor instead.
func (*SemesterLecture) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{11}
}

func (x *SemesterLecture) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SemesterLecture) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SemesterLecture) GetXuinya1() *Xuinya5 {
	if x != nil {
		return x.Xuinya1
	}
	return nil
}

func (x *SemesterLecture) GetXuinya2() *Xuinya5 {
	if x != nil {
		return x.Xuinya2
	}
	return nil
}

type Xuinya5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zalupa        int32                  `protobuf:"varint,1,opt,name=zalupa,proto3" json:"zalupa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Xuinya5) Reset() {
	*x = Xuinya5{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Xuinya5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Xuinya5) ProtoMessage() {}

func (x *Xuinya5) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Xuinya5.ProtoReflect.Descriptor instead.
func (*Xuinya5) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{12}
}

func (x *Xuinya5) GetZalupa() int32 {
	if x != nil {
		return x.Zalupa
	}
	return 0
}

type Xuinya6 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Zalupa        int32                  `protobuf:"varint,2,opt,name=zalupa,proto3" json:"zalupa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Xuinya6) Reset() {
	*x = Xuinya6{}
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Xuinya6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Xuinya6) ProtoMessage() {}

func (x *Xuinya6) ProtoReflect() protoreflect.Message {
	mi := &file_SelfApproveAttendanceResponse_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Xuinya6.ProtoReflect.Descriptor instead.
func (*Xuinya6) Descriptor() ([]byte, []int) {
	return file_SelfApproveAttendanceResponse_proto_rawDescGZIP(), []int{13}
}

func (x *Xuinya6) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Xuinya6) GetZalupa() int32 {
	if x != nil {
		return x.Zalupa
	}
	return 0
}

var File_SelfApproveAttendanceResponse_proto protoreflect.FileDescriptor

var file_SelfApproveAttendanceResponse_proto_rawDesc = string([]byte{
	0x0a, 0x23, 0x53, 0x65, 0x6c, 0x66, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x41, 0x74, 0x74,
	0x65, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x74,
	0x0a, 0x1d, 0x53, 0x65, 0x6c, 0x66, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x41, 0x74, 0x74,
	0x65, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x27, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x1e, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x8e, 0x03, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x70, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43,
	0x61, 0x6d, 0x70, 0x75, 0x73, 0x52, 0x06, 0x63, 0x61, 0x6d, 0x70, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x78, 0x75,
	0x69, 0x6e, 0x79, 0x61, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x58, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x32, 0x52, 0x07, 0x78,
	0x75, 0x69, 0x6e, 0x79, 0x61, 0x32, 0x12, 0x2a, 0x0a, 0x07, 0x78, 0x75, 0x69, 0x6e, 0x79, 0x61,
	0x33, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x58, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x32, 0x52, 0x07, 0x78, 0x75, 0x69, 0x6e, 0x79,
	0x61, 0x33, 0x12, 0x2a, 0x0a, 0x07, 0x78, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x34, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x58, 0x75,
	0x69, 0x6e, 0x79, 0x61, 0x33, 0x52, 0x07, 0x78, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x34, 0x12, 0x2a,
	0x0a, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65,
	0x72, 0x52, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x05, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x75, 0x69, 0x64, 0x32,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x75, 0x69, 0x64, 0x32, 0x12, 0x16, 0x0a,
	0x06, 0x78, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x78,
	0x75, 0x69, 0x6e, 0x79, 0x61, 0x22, 0x4a, 0x0a, 0x06, 0x43, 0x61, 0x6d, 0x70, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x78, 0x75, 0x69, 0x79, 0x6e, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x78, 0x75, 0x69, 0x79, 0x6e, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x22, 0x22, 0x0a, 0x06, 0x58, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x12, 0x18, 0x0a, 0x06, 0x7a,
	0x61, 0x6c, 0x75, 0x70, 0x61, 0x18, 0x8a, 0xd2, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x7a,
	0x61, 0x6c, 0x75, 0x70, 0x61, 0x22, 0x21, 0x0a, 0x07, 0x58, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x32,
	0x12, 0x16, 0x0a, 0x06, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x22, 0x71, 0x0a, 0x07, 0x58, 0x75, 0x69, 0x6e,
	0x79, 0x61, 0x33, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x31, 0x12, 0x18, 0x0a,
	0x07, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x61, 0x6c, 0x75, 0x70,
	0x61, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61,
	0x33, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x34, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x34, 0x22, 0x8d, 0x01, 0x0a, 0x07,
	0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x3a, 0x0a, 0x0a, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x69,
	0x64, 0x64, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52,
	0x0a, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x11, 0x4d,
	0x69, 0x64, 0x64, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xf4, 0x01, 0x0a, 0x0c, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x75, 0x69, 0x64, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x75, 0x75, 0x69, 0x64, 0x32, 0x12, 0x28, 0x0a, 0x06, 0x78, 0x75, 0x69, 0x6e, 0x79,
	0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x58, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x34, 0x52, 0x06, 0x78, 0x75, 0x69, 0x6e, 0x79,
	0x61, 0x12, 0x34, 0x0a, 0x08, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65,
	0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x08, 0x73,
	0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x78, 0x75, 0x69, 0x6e, 0x79,
	0x61, 0x32, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x78, 0x75, 0x69, 0x6e, 0x79, 0x61,
	0x32, 0x12, 0x2a, 0x0a, 0x07, 0x78, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x33, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x58, 0x75, 0x69,
	0x6e, 0x79, 0x61, 0x36, 0x52, 0x07, 0x78, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x33, 0x22, 0x3d, 0x0a,
	0x07, 0x58, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x34, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x61, 0x6c, 0x75,
	0x70, 0x61, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x7a, 0x61, 0x6c, 0x75, 0x70,
	0x61, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x32, 0x22, 0x93, 0x01, 0x0a,
	0x0f, 0x53, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x78, 0x75,
	0x69, 0x6e, 0x79, 0x61, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x58, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x35, 0x52, 0x07, 0x78,
	0x75, 0x69, 0x6e, 0x79, 0x61, 0x31, 0x12, 0x2a, 0x0a, 0x07, 0x78, 0x75, 0x69, 0x6e, 0x79, 0x61,
	0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x58, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x35, 0x52, 0x07, 0x78, 0x75, 0x69, 0x6e, 0x79,
	0x61, 0x32, 0x22, 0x21, 0x0a, 0x07, 0x58, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x35, 0x12, 0x16, 0x0a,
	0x06, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x7a,
	0x61, 0x6c, 0x75, 0x70, 0x61, 0x22, 0x35, 0x0a, 0x07, 0x58, 0x75, 0x69, 0x6e, 0x79, 0x61, 0x36,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x7a, 0x61, 0x6c, 0x75, 0x70, 0x61, 0x42, 0x11, 0x5a, 0x0f,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_SelfApproveAttendanceResponse_proto_rawDescOnce sync.Once
	file_SelfApproveAttendanceResponse_proto_rawDescData []byte
)

func file_SelfApproveAttendanceResponse_proto_rawDescGZIP() []byte {
	file_SelfApproveAttendanceResponse_proto_rawDescOnce.Do(func() {
		file_SelfApproveAttendanceResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SelfApproveAttendanceResponse_proto_rawDesc), len(file_SelfApproveAttendanceResponse_proto_rawDesc)))
	})
	return file_SelfApproveAttendanceResponse_proto_rawDescData
}

var file_SelfApproveAttendanceResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_SelfApproveAttendanceResponse_proto_goTypes = []any{
	(*SelfApproveAttendanceResponse)(nil), // 0: message.SelfApproveAttendanceResponse
	(*Failed)(nil),                        // 1: message.Failed
	(*Success)(nil),                       // 2: message.Success
	(*Campus)(nil),                        // 3: message.Campus
	(*Xuinya)(nil),                        // 4: message.Xuinya
	(*Xuinya2)(nil),                       // 5: message.Xuinya2
	(*Xuinya3)(nil),                       // 6: message.Xuinya3
	(*Teacher)(nil),                       // 7: message.Teacher
	(*MiddlenameTeacher)(nil),             // 8: message.MiddlenameTeacher
	(*GroupLecture)(nil),                  // 9: message.GroupLecture
	(*Xuinya4)(nil),                       // 10: message.Xuinya4
	(*SemesterLecture)(nil),               // 11: message.SemesterLecture
	(*Xuinya5)(nil),                       // 12: message.Xuinya5
	(*Xuinya6)(nil),                       // 13: message.Xuinya6
}
var file_SelfApproveAttendanceResponse_proto_depIdxs = []int32{
	1,  // 0: message.SelfApproveAttendanceResponse.failed:type_name -> message.Failed
	2,  // 1: message.SelfApproveAttendanceResponse.success:type_name -> message.Success
	3,  // 2: message.Success.campus:type_name -> message.Campus
	5,  // 3: message.Success.xuinya2:type_name -> message.Xuinya2
	5,  // 4: message.Success.xuinya3:type_name -> message.Xuinya2
	6,  // 5: message.Success.xuinya4:type_name -> message.Xuinya3
	7,  // 6: message.Success.teacher:type_name -> message.Teacher
	9,  // 7: message.Success.group:type_name -> message.GroupLecture
	8,  // 8: message.Teacher.middleName:type_name -> message.MiddlenameTeacher
	10, // 9: message.GroupLecture.xuinya:type_name -> message.Xuinya4
	11, // 10: message.GroupLecture.semester:type_name -> message.SemesterLecture
	13, // 11: message.GroupLecture.xuinya3:type_name -> message.Xuinya6
	12, // 12: message.SemesterLecture.xuinya1:type_name -> message.Xuinya5
	12, // 13: message.SemesterLecture.xuinya2:type_name -> message.Xuinya5
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_SelfApproveAttendanceResponse_proto_init() }
func file_SelfApproveAttendanceResponse_proto_init() {
	if File_SelfApproveAttendanceResponse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SelfApproveAttendanceResponse_proto_rawDesc), len(file_SelfApproveAttendanceResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SelfApproveAttendanceResponse_proto_goTypes,
		DependencyIndexes: file_SelfApproveAttendanceResponse_proto_depIdxs,
		MessageInfos:      file_SelfApproveAttendanceResponse_proto_msgTypes,
	}.Build()
	File_SelfApproveAttendanceResponse_proto = out.File
	file_SelfApproveAttendanceResponse_proto_goTypes = nil
	file_SelfApproveAttendanceResponse_proto_depIdxs = nil
}
